const test=require('node:test');const assert=require('node:assert/strict');const E=require('../games/frit-academy/engine.js');
let seed=73191;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
test('all five modules and three levels generate sound, solvable learning tasks in both languages',()=>{for(const lang of ['nl','fr'])for(const module of E.modules)for(let level=1;level<=3;level++)for(let n=0;n<1000;n++){const q=E.make(module,level,lang,rng);let answer;if(module==='fries'){answer=q.targets;assert(q.targets.every(n=>n>=1&&n<=10));assert.equal(q.targets.reduce((a,b)=>a+b),q.total);assert(!E.check(q,q.targets.map(n=>n+1)));}if(module==='sauce'){if(q.kind==='pattern'){answer=q.answer;assert.equal(q.pattern[q.missing],answer);assert(!E.check(q,1-answer));let run=0,last;for(const x of q.pattern){run=x===last?run+1:1;last=x;assert(run<=3);}}else{assert(Number.isInteger(q.red));answer=Array(q.red).fill(0).concat(Array(q.total-q.red).fill(1));assert(!E.check(q,Array(q.total).fill(0)));assert(!E.check(q,Array(q.total).fill(null)));}}if(module==='spelling'){answer=q.word;for(const c of q.word)assert(q.tiles.some(t=>t.letter===c));assert.equal(new Set(q.tiles.map(t=>t.id)).size,q.tiles.length);assert(!E.check(q,q.word.slice(1)));}if(module==='cash'){answer=q.target;assert(Number.isInteger(answer)&&answer>0);assert(q.denominations.includes(100));if(level>1)assert(q.denominations.includes(1));assert.equal(q.target,q.kind==='change'?q.paid-q.price:q.price);assert(!E.check(q,answer+1));}if(module==='time'){answer=q.answer;assert(answer>=0&&answer<1440&&answer%5===0);assert.equal(answer,q.kind==='schedule'?q.start-q.duration:q.start+q.duration);assert(!E.check(q,answer+5));}assert(E.check(q,answer));}});
const event=(n,overrides={})=>({id:String(n),profile_id:'p',profile_name:'Chef',module:'fries',level:1,attempts:1,assisted:false,completed_at:new Date(1700000000000+n*1000).toISOString(),...overrides});
test('difficulty advances on five of six unassisted successes, never on assisted repetition',()=>{assert.equal(E.stats(Array.from({length:6},(_,i)=>event(i)),'fries').level,2);assert.equal(E.stats(Array.from({length:6},(_,i)=>event(i,{assisted:true})),'fries').level,1);assert.equal(E.stats(Array.from({length:6},(_,i)=>event(i,{attempts:i<2?2:1})),'fries').level,1);const rows=[...Array.from({length:6},(_,i)=>event(i)),...Array.from({length:6},(_,i)=>event(i+6,{level:2,attempts:2}))];assert.equal(E.stats(rows,'fries').level,1);});
test('cross-device merge is idempotent and preserves both devices events',()=>{const a=[event(1),event(2)],b=[event(2),event(3)];assert.equal(E.merge(a,b).length,3);assert.deepEqual(E.merge(a,b),E.merge(b,a));assert.deepEqual(E.merge(E.merge(a,b),a),E.merge(a,b));});
test('unlocks require completed orders and mastery badges require independent successes',()=>{assert.equal(E.rewards([]).decorations,0);assert.equal(E.rewards(Array.from({length:24},(_,i)=>event(i))).location,2);assert.equal(E.rewards(Array.from({length:6},(_,i)=>event(i,{assisted:true}))).mastered.length,0);assert.deepEqual(E.rewards(Array.from({length:6},(_,i)=>event(i))).mastered,['fries']);});
test('malformed persisted records are rejected',()=>{assert(E.validEvent(event(1)));assert(!E.validEvent(event(1,{module:'unknown'})));assert(!E.validEvent(event(1,{attempts:0})));assert(!E.validEvent(event(1,{completed_at:'invalid'})));});

test('analog clocks accept both equivalent 12-hour and 24-hour readings, without accepting incomplete answers',()=>{const q={module:'time',kind:'read',answer:13*60};assert(E.check(q,60));assert(E.check(q,13*60));assert(!E.check(q,null));assert(!E.check(q,65));assert(!E.check(q,1500));});
