const test=require('node:test'),assert=require('node:assert/strict');require('../games/moonlight-hollow/engine.js');const C=require('../games/moonlight-hollow/campaign.js');
function solution(q){if(q.type==='groups')return q.targets;if(q.type==='fraction')return Array(q.moon).fill(0).concat(Array(q.total-q.moon).fill(1));if(q.type==='word'){const used=new Set();return Array.from(q.word).map(letter=>{const v=q.tiles.find(v=>v.letter===letter&&!used.has(v.id));used.add(v.id);return v.id;});}if(q.type==='time')return q.answer;if(q.type==='mirror')return q.mirrors.map(v=>v.solution);return q.answer;}
test('all 30 quests in both languages and three levels are solvable across 18,000 variations',()=>{for(const lang of ['nl','fr'])for(let level=1;level<=3;level++)for(let index=0;index<30;index++)for(let seed=0;seed<100;seed++){const q=C.make(index,level,lang,seed);assert.equal(C.check(q,solution(q)),true,JSON.stringify(q));assert.equal(C.check(q,C.initial(q)),false,'puzzle must start unsolved');}});
test('fractions have integer portions and bridge totals conserve fireflies',()=>{for(let i=0;i<30;i++)for(let level=1;level<=3;level++){const q=C.make(i,level);if(q.type==='fraction'){assert(Number.isInteger(q.moon));assert(q.moon>0&&q.moon<q.total);}if(q.type==='groups')assert.equal(q.pool,q.total-q.initial);}});
test('word construction rejects repeated tile IDs',()=>{const q=C.make(7,1);assert.equal(C.check(q,Array(q.word.length).fill(q.tiles[0].id)),false);});
test('route accepts multiple correct paths and rejects overshoots',()=>{const q=C.make(15,2);assert(C.check(q,'ENEN'));assert(C.check(q,'NNEE'));assert(!C.check(q,'EEEEE'));assert(!C.check(q,'EN'));});
test('campaign uses distinct completions and does not advance for old practice records',()=>{const events=[{area:'bridge',level:1,attempts:1,assisted:false}];assert.equal(C.next(events),0);for(let quest=0;quest<30;quest++){events.push({quest});assert.equal(C.next(events),quest+1);}events.push({quest:0},{quest:999});assert.equal(C.completed(events).size,30);assert.equal(C.chapter(events),4);});
test('proficiency is per skill and hints do not count as independent mastery',()=>{const events=Array.from({length:5},()=>({area:'bridge',attempts:1,assisted:false}));assert.equal(C.skill(events,'bridge'),3);assert.equal(C.skill(events,'garden'),1);events.forEach(e=>e.assisted=true);assert.equal(C.skill(events,'bridge'),1);});
test('saved puzzles are reproducible without random rerolls',()=>{assert.deepEqual(C.make(13,3,'fr',7),C.make(13,3,'fr',7));assert(!C.validateDraft({q:{index:100}}));});
