(function(root){
'use strict';
const modules=['fries','sauce','spelling','cash','time'];
const words={nl:[['friet','🍟','Lange, gele hapjes.'],['saus','🥣','Dit doe je op je frietjes.'],['zout','🧂','Een klein beetje op de friet.'],['kok','🧑‍🍳','Deze persoon kookt.'],['pan','🍳','Hierin bak je eten.'],['zak','🛍️','Hierin draag je je bestelling.'],['aardappel','🥔','Hiervan maken we frietjes.'],['ketchup','🍅','Een rode saus met tomaten.'],['schort','🧑‍🍳','Dit beschermt de kleren van de kok.'],['tomaat','🍅','Een rode groente voor saus.'],['bestelling','📝','Wat de klant wil eten.'],['mayonaise','🥣','Een lichte saus op de frietjes.'],['krokant','🍟','Frietjes die lekker knapperig zijn.']],fr:[['sel','🧂','On en met un peu sur les frites.'],['sac','🛍️','Pour emporter la commande.'],['bol','🥣','Un petit récipient.'],['chef','🧑‍🍳','La personne qui cuisine.'],['frite','🍟','Un long morceau de pomme de terre.'],['sauce','🥣','On la met sur les frites.'],['pomme','🥔','Le premier mot de « pomme de terre ».'],['tomate','🍅','Un ingrédient rouge du ketchup.'],['fromage','🧀','Un aliment fait avec du lait.'],['tablier','🧑‍🍳','Il protège les vêtements du chef.'],['commande','📝','Ce que le client veut manger.'],['mayonnaise','🥣','Une sauce claire pour les frites.'],['croustillant','🍟','Le contraire de mou.']]};
function shuffle(a,rng=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function make(module,level=1,lang='nl',rng=Math.random){
if(!modules.includes(module))throw Error('Unknown station');level=Math.max(1,Math.min(3,level));const int=(a,b)=>a+Math.floor(rng()*(b-a+1));let q={module,level,lang};
if(module==='fries'){q.kind=level===1?'count':level===2?'split':'groups';q.targets=level===1?[int(4,10)]:level===2?[10,int(1,9)]:Array(int(2,4)).fill(int(2,5));q.total=q.targets.reduce((a,b)=>a+b,0);}
if(module==='sauce'){if(level===1){q.kind='pattern';const p=[[0,1],[0,0,1],[0,1,1]][int(0,2)];q.pattern=Array.from({length:p.length*2+1},(_,i)=>p[i%p.length]);q.missing=int(p.length,q.pattern.length-1);q.answer=q.pattern[q.missing];}else{q.kind=level===2?'fraction':'ratio';q.denominator=level===2?[2,4][int(0,1)]:[3,4][int(0,1)];q.numerator=level===2&&q.denominator===4?int(1,3):1;q.total=q.denominator*int(1,3);q.red=q.total*q.numerator/q.denominator;}}
if(module==='spelling'){const pool=words[lang]||words.nl;const range=level===1?[0,5]:level===2?[6,9]:[10,12];const w=pool[int(...range)];q.word=w[0].toUpperCase();q.icon=w[1];q.clue=w[2];q.tiles=shuffle([...q.word,...(level===3?['X','Z']:[])].map((letter,id)=>({letter,id})),rng);}
if(module==='cash'){q.kind=level===3?'change':'pay';q.price=level===1?int(2,10)*100:level===2?int(2,9)*100+int(1,19)*5:int(2,14)*100+int(0,19)*5;q.paid=q.kind==='change'?[500,1000,2000].find(v=>v>q.price):q.price;q.target=q.paid-q.price;if(q.kind==='pay')q.target=q.price;q.denominations=level===1?[1000,500,200,100]:[2000,1000,500,200,100,50,20,10,5,2,1];}
if(module==='time'){q.kind=level===1?'read':level===2?'elapsed':'schedule';q.start=int(8,18)*60+(level===1?0:int(0,11)*5);q.duration=level===1?0:int(1,5)*5;q.answer=q.kind==='schedule'?q.start-q.duration:q.start+q.duration;}
return q;
}
function check(q,a){if(q.module==='fries')return Array.isArray(a)&&a.length===q.targets.length&&a.every((v,i)=>v===q.targets[i]);if(q.module==='sauce')return q.kind==='pattern'?a===q.answer:Array.isArray(a)&&a.length===q.total&&a.every(v=>v===0||v===1)&&a.filter(v=>v===0).length===q.red;if(q.module==='spelling')return a===q.word;if(q.module==='cash')return a===q.target;if(q.module==='time')return a===q.answer;return false;}
function stats(events,module){const rows=events.filter(e=>e.module===module).sort((a,b)=>a.completed_at.localeCompare(b.completed_at)||a.id.localeCompare(b.id));let level=1,batch=[];for(const e of rows){if(e.level!==level){batch=[];continue;}batch.push(e);if(batch.length===6){const wins=batch.filter(x=>x.attempts===1&&!x.assisted).length;if(wins>=5)level=Math.min(3,level+1);else if(wins<=2)level=Math.max(1,level-1);batch=[];}}const independent=rows.filter(e=>e.attempts===1&&!e.assisted);return {level,total:rows.length,independent:independent.length,recent:rows.slice(-6),early:rows.slice(0,6)};}
function rewards(events){const n=events.length,mastered=modules.filter(m=>stats(events,m).independent>=6);return {decorations:n>=15?3:n>=8?2:n>=3?1:0,recipes:n>=12?2:n>=5?1:0,customers:n>=10?2:n>=4?1:0,location:n>=24?2:n>=12?1:0,mastered};}
function merge(a,b){const map=new Map(a.map(x=>[x.id,x]));b.forEach(x=>{if(!map.has(x.id))map.set(x.id,x);});return [...map.values()].sort((a,b)=>a.completed_at.localeCompare(b.completed_at)||a.id.localeCompare(b.id));}
function validEvent(e){return e&&typeof e.id==='string'&&typeof e.profile_id==='string'&&typeof e.profile_name==='string'&&e.profile_name.length<=24&&modules.includes(e.module)&&[1,2,3].includes(e.level)&&Number.isInteger(e.attempts)&&e.attempts>=1&&e.attempts<=100&&typeof e.assisted==='boolean'&&Number.isFinite(Date.parse(e.completed_at));}
const api={modules,words,shuffle,make,check,stats,rewards,merge,validEvent};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FritEngine=api;
})(typeof window==='undefined'?globalThis:window);
