/* Original local soundtrack + Foley playback. No external audio service or autoplay. */
(function(root){'use strict';
const TRACKS=['menu','village','woods','garden','library','tower','castle','festival'];
const EFFECTS=['ui','back','pickup','place','remove','tile','stone','pour','bubble','bottle','letter','page','clock','mirror','pattern','hint','retry','solve','lantern','path','chapter','festival','train','ghost','reset','riddle','leaf','footstep-stone','footstep-leaves','footstep-wood'];
const AREAS={bridge:'woods',garden:'garden',library:'library',clock:'tower',lights:'castle'};
const SITES={bridge:[-21,-13],garden:[19,-13],library:[-22,20],clock:[20,21],lights:[0,43]};
function environment(x,z,forced=null){if(forced&&AREAS[forced])return AREAS[forced];let area='village',best=16;for(const [key,p]of Object.entries(SITES)){const d=Math.hypot(x-p[0],z-p[1]);if(d<best){best=d;area=AREAS[key];}}return area;}
function volume(p,key){return p.muted?0:Math.max(0,Math.min(100,Number(p[key])||0))/100;}
function create(config){let ctx=null,musicBus,effectsBus,ambienceBus,master,compressor,unlocked=false,paused=false,desired='menu',current=null,ambient=null,musicRequest=0,ambientRequest=0,duck=1,previewUntil=0,festivalLocked=false,last={};const buffers=new Map(),pending=new Map(),voices=new Set(),loops=new Set();
const report=msg=>config.status?.(msg);
async function load(name,kind='effects'){const key=kind+':'+name;if(buffers.has(key))return buffers.get(key);if(pending.has(key))return pending.get(key);const extension=kind==='effects'?'wav':'mp3',path='audio/'+name+'.'+extension;const promise=fetch(path).then(r=>{if(!r.ok)throw Error(path);return r.arrayBuffer();}).then(data=>ctx.decodeAudioData(data)).then(buffer=>{buffers.set(key,buffer);return buffer;}).finally(()=>pending.delete(key));pending.set(key,promise);return promise;}
function gains(){if(!ctx)return;const p=config.prefs(),now=ctx.currentTime;musicBus.gain.setTargetAtTime(volume(p,'music')*.42*duck,now,.14);effectsBus.gain.setTargetAtTime(volume(p,'effects')*.65,now,.08);ambienceBus.gain.setTargetAtTime(volume(p,'effects')*.48,now,.3);}
async function unlock(){if(ctx&&unlocked&&!paused&&ctx.state==='running')return true;if(!ctx){try{ctx=new(root.AudioContext||root.webkitAudioContext)();master=ctx.createGain();master.gain.value=.8;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.008;compressor.release.value=.22;master.connect(compressor);compressor.connect(ctx.destination);musicBus=ctx.createGain();effectsBus=ctx.createGain();ambienceBus=ctx.createGain();musicBus.connect(master);effectsBus.connect(master);ambienceBus.connect(master);gains();}catch(_){report('unsupported');return false;}}unlocked=true;paused=false;try{await ctx.resume();}catch(_){report('blocked');return false;}if(ctx.state!=='running'){report('blocked');return false;}report('ready');if(!current&&volume(config.prefs(),'music'))setMusic(desired,{lock:festivalLocked});if(!ambient)setAmbience(desired==='menu'||desired==='festival'?'village':desired);return true;}
function loopSource(buffer,bus){const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=0;source.connect(gain);gain.connect(bus);source.start();const pair={source,gain,stopped:false};loops.add(pair);source.onended=()=>{loops.delete(pair);source.disconnect();gain.disconnect();};return pair;}
function fadeStop(pair,duration=1.8){if(!pair||pair.stopped)return;pair.stopped=true;const now=ctx.currentTime;pair.gain.gain.cancelScheduledValues(now);pair.gain.gain.setValueAtTime(pair.gain.gain.value,now);pair.gain.gain.linearRampToValueAtTime(0,now+duration);try{pair.source.stop(now+duration+.05);}catch(_){}}
async function setMusic(name,{preview=false,lock=false}={}){if(!TRACKS.includes(name))name='village';desired=name;if(!preview)festivalLocked=!!lock;if(preview)previewUntil=Date.now()+15000;if(!ctx||!unlocked||paused)return;if(current?.name===name)return;const request=++musicRequest;try{const buffer=await load(name,'music');if(request!==musicRequest||paused)return;const pair=loopSource(buffer,musicBus);pair.name=name;pair.gain.gain.linearRampToValueAtTime(1,ctx.currentTime+1.8);fadeStop(current);current=pair;report('music-playing');}catch(_){report('missing');}}
async function setAmbience(name){if(!['village','woods','garden','library','tower','castle'].includes(name))name='village';if(!ctx||!unlocked||paused||ambient?.name===name)return;const request=++ambientRequest;try{const buffer=await load('ambient-'+name,'ambience');if(request!==ambientRequest||paused)return;const pair=loopSource(buffer,ambienceBus);pair.name=name;pair.gain.gain.linearRampToValueAtTime(1,ctx.currentTime+2);fadeStop(ambient,2);ambient=pair;}catch(_){report('missing');}}
async function play(kind,{pan=0,gain=1,force=false}={}){if(!EFFECTS.includes(kind))kind='place';if(!unlocked||!ctx||paused||!volume(config.prefs(),'effects'))return;const now=Date.now(),gap=kind.startsWith('footstep')?210:kind==='clock'||kind==='mirror'?70:35;if(!force&&now-(last[kind]||0)<gap)return;last[kind]=now;try{const buffer=await load(kind);if(paused||!volume(config.prefs(),'effects'))return;if(voices.size>=12){const oldest=voices.values().next().value;try{oldest.stop();}catch(_){}}const source=ctx.createBufferSource(),g=ctx.createGain();source.buffer=buffer;g.gain.value=Math.max(0,Math.min(1,gain));source.connect(g);let panner;if(ctx.createStereoPanner){panner=ctx.createStereoPanner();panner.pan.value=Math.max(-1,Math.min(1,pan));g.connect(panner);panner.connect(effectsBus);}else g.connect(effectsBus);voices.add(source);source.onended=()=>{voices.delete(source);source.disconnect();g.disconnect();panner?.disconnect();};source.start();report('effect-playing');}catch(_){report('missing');}}
function position(x,z,forced=null){const name=environment(x,z,forced);if(Date.now()>previewUntil&&!festivalLocked)setMusic(name);setAmbience(name);}
function stop(){paused=true;musicRequest++;ambientRequest++;for(const source of voices){try{source.stop();}catch(_){}}voices.clear();for(const pair of loops)fadeStop(pair,.08);current=null;ambient=null;}
async function suspend(){paused=true;previewUntil=0;musicRequest++;ambientRequest++;if(ctx)await ctx.suspend().catch(()=>{});}
async function resume(){if(!ctx||!unlocked)return;paused=false;await ctx.resume().catch(()=>{});if(!current)setMusic(desired,{lock:festivalLocked});if(!ambient)setAmbience(desired);}
function narration(active){duck=active?.25:1;gains();}
function testMusic(name){unlock().then(ok=>{if(ok)setMusic(name,{preview:true});});}
function testEffect(name){unlock().then(ok=>{if(ok)play(name,{force:true});});}
function preloadEffects(){if(!ctx)return;Promise.allSettled(EFFECTS.map(name=>load(name))).then(rows=>{if(rows.some(r=>r.status==='rejected'))report('missing');});}
return{unlock,play,setMusic,setAmbience,position,update:gains,suspend,resume,narration,testMusic,testEffect,preloadEffects,stop,destroy(){stop();ctx?.close().catch(()=>{});},state(){return{unlocked,paused,music:current?.name,ambience:ambient?.name,voices:voices.size,loops:loops.size};}};
}
const api={create,TRACKS,EFFECTS,AREAS,environment,volume};if(typeof module!=='undefined')module.exports=api;root.MoonAudio=api;
})(typeof window!=='undefined'?window:globalThis);
