/* Original local soundtrack + Foley playback. No external audio service or autoplay. */
(function(root){'use strict';
const TRACKS=['menu','village','woods','garden','library','tower','castle','festival'];
const EFFECTS=['ui','back','pickup','place','remove','tile','stone','pour','bubble','bottle','letter','page','clock','mirror','pattern','hint','retry','solve','lantern','path','chapter','festival','train','ghost','reset','riddle','leaf','footstep-stone','footstep-leaves','footstep-wood','thunder'];
const AREAS={bridge:'woods',garden:'garden',library:'library',clock:'tower',lights:'castle'};
const SITES={bridge:[-21,-13],garden:[19,-13],library:[-22,20],clock:[20,21],lights:[0,43]};
function environment(x,z,forced=null){if(forced&&AREAS[forced])return AREAS[forced];let area='village',best=root.MoonLandscape?22:16;const sites=root.MoonLandscape?Object.fromEntries(Object.entries(root.MoonLandscape.sites).map(([k,p])=>[k,[p.x,p.z]])):SITES;for(const [key,p]of Object.entries(sites)){const d=Math.hypot(x-p[0],z-p[1]);if(d<best){best=d;area=AREAS[key];}}return area;}
function volume(p,key){return p.muted?0:Math.max(0,Math.min(100,Number(p[key])||0))/100;}
function create(config){let ctx=null,musicBus,effectsBus,ambienceBus,master,compressor,analyser,unlocked=false,paused=false,desired='menu',ambientDesired='village',current=null,ambient=null,musicRequest=0,ambientRequest=0,effectRequest=0,loadingMusic=null,loadingAmbient=null,duck=1,previewUntil=0,festivalLocked=false,last={};const buffers=new Map(),pending=new Map(),voices=new Set(),loops=new Set(),spatial=new Map();
let listenerPose=null;
const vector=v=>v&&[v.x,v.y,v.z].every(Number.isFinite);
function setPosition(node,p){if(!vector(p))return;if(node.positionX){node.positionX.value=p.x;node.positionY.value=p.y;node.positionZ.value=-p.z;}else node.setPosition?.(p.x,p.y,-p.z);}
function listener(p,forward,up={x:0,y:1,z:0}){if(!vector(p)||!vector(forward)||!vector(up))return;listenerPose={p,forward,up};updateSpatial();}
function updateSpatial(){if(!ctx)return;const l=ctx.listener;if(l&&listenerPose){const {p,forward:f,up:u}=listenerPose;setPosition(l,p);if(l.forwardX){for(const [key,v]of Object.entries({forwardX:f.x,forwardY:f.y,forwardZ:-f.z,upX:u.x,upY:u.y,upZ:-u.z}))l[key].value=v;}else l.setOrientation?.(f.x,f.y,-f.z,u.x,u.y,-u.z);}
 for(const {panner,point}of spatial.values())setPosition(panner,typeof point==='function'?point():point);
}
const report=(msg,detail)=>config.status?.(msg,detail);
async function load(name,kind='effects'){const key=kind+':'+name;if(buffers.has(key))return buffers.get(key);if(pending.has(key))return pending.get(key);const extension=kind==='effects'?'wav':'mp3',path='audio/'+name+'.'+extension;const promise=fetch(path).then(r=>{if(!r.ok)throw Error(path);return r.arrayBuffer();}).then(data=>ctx.decodeAudioData(data)).then(buffer=>{buffers.set(key,buffer);return buffer;}).finally(()=>pending.delete(key));pending.set(key,promise);return promise;}
function gains(){if(!ctx||!musicBus)return;const p=config.prefs(),now=ctx.currentTime;musicBus.gain.setTargetAtTime(volume(p,'music')*.8*duck,now,.14);effectsBus.gain.setTargetAtTime(volume(p,'effects')*.85,now,.08);ambienceBus.gain.setTargetAtTime(volume(p,'effects')*.35,now,.3);}
function ensureLoops(){if(!ctx||paused||ctx.state!=='running')return;if(volume(config.prefs(),'music'))setMusic(desired,{lock:festivalLocked});if(volume(config.prefs(),'effects'))setAmbience(ambientDesired);}
async function unlock(){
if(ctx&&unlocked&&!paused&&ctx.state==='running'){gains();ensureLoops();return true;}
// iOS otherwise treats Web Audio as game/ambient audio and can silence it with the ringer switch.
try{if(root.navigator?.audioSession)root.navigator.audioSession.type='playback';}catch(_){}
if(!ctx){try{ctx=new(root.AudioContext||root.webkitAudioContext)();master=ctx.createGain();master.gain.value=.9;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.008;compressor.release.value=.22;master.connect(compressor);if(ctx.createAnalyser){analyser=ctx.createAnalyser();analyser.fftSize=2048;compressor.connect(analyser);analyser.connect(ctx.destination);}else compressor.connect(ctx.destination);musicBus=ctx.createGain();effectsBus=ctx.createGain();ambienceBus=ctx.createGain();musicBus.connect(master);effectsBus.connect(master);ambienceBus.connect(master);gains();ctx.onstatechange=()=>{if(!paused&&ctx.state!=='running'&&ctx.state!=='closed')report('blocked');};}catch(_){ctx=null;report('unsupported');return false;}}
paused=false;
// Start a silent buffer synchronously inside the gesture, before fetching or decoding files.
// Some Safari versions require a source start as well as resume().
try{const warm=ctx.createBufferSource();warm.buffer=ctx.createBuffer(1,1,ctx.sampleRate);warm.connect(ctx.destination);warm.onended=()=>warm.disconnect();warm.start();await ctx.resume();}catch(_){report('blocked');return false;}
if(paused||ctx.state!=='running'){if(!paused)report('blocked');return false;}unlocked=true;report('ready');ensureLoops();return true;
}
function loopSource(buffer,bus){const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=0;source.connect(gain);gain.connect(bus);source.start();const pair={source,gain,stopped:false};loops.add(pair);source.onended=()=>{loops.delete(pair);source.disconnect();gain.disconnect();};return pair;}
function fadeStop(pair,duration=1.8){if(!pair||pair.stopped)return;pair.stopped=true;const now=ctx.currentTime;pair.gain.gain.cancelScheduledValues(now);pair.gain.gain.setValueAtTime(pair.gain.gain.value,now);pair.gain.gain.linearRampToValueAtTime(0,now+duration);try{pair.source.stop(now+duration+.05);}catch(_){}}
function setMusic(name,{preview=false,lock=false}={}){if(!TRACKS.includes(name))name='village';desired=name;if(!preview)festivalLocked=!!lock;if(preview)previewUntil=Date.now()+15000;if(!ctx||!unlocked||paused)return Promise.resolve(false);if(current?.name===name){if(loadingMusic&&loadingMusic.name!==name){musicRequest++;loadingMusic=null;}return Promise.resolve(true);}if(loadingMusic?.name===name)return loadingMusic.promise;const request=++musicRequest,entry={name};loadingMusic=entry;entry.promise=(async()=>{try{const buffer=await load(name,'music');if(request!==musicRequest||paused)return false;const pair=loopSource(buffer,musicBus);pair.name=name;pair.gain.gain.setValueAtTime(0,ctx.currentTime);pair.gain.gain.linearRampToValueAtTime(1,ctx.currentTime+1.8);fadeStop(current);current=pair;report('music-playing');return true;}catch(_){if(request===musicRequest)report('missing','audio/'+name+'.mp3');return false;}finally{if(loadingMusic===entry)loadingMusic=null;}})();return entry.promise;}
function setAmbience(name){if(!['village','woods','garden','library','tower','castle'].includes(name))name='village';ambientDesired=name;if(!ctx||!unlocked||paused)return Promise.resolve(false);if(ambient?.name===name){if(loadingAmbient&&loadingAmbient.name!==name){ambientRequest++;loadingAmbient=null;}return Promise.resolve(true);}if(loadingAmbient?.name===name)return loadingAmbient.promise;const request=++ambientRequest,entry={name};loadingAmbient=entry;entry.promise=(async()=>{try{const buffer=await load('ambient-'+name,'ambience');if(request!==ambientRequest||paused)return false;const pair=loopSource(buffer,ambienceBus);pair.name=name;pair.gain.gain.setValueAtTime(0,ctx.currentTime);pair.gain.gain.linearRampToValueAtTime(1,ctx.currentTime+2);fadeStop(ambient,2);ambient=pair;return true;}catch(_){if(request===ambientRequest)report('missing','audio/ambient-'+name+'.mp3');return false;}finally{if(loadingAmbient===entry)loadingAmbient=null;}})();return entry.promise;}
async function play(kind,{pan=0,gain=1,force=false,point=null,refDistance=6}={}){if(!EFFECTS.includes(kind))kind='place';if(!unlocked||!ctx||paused||ctx.state!=='running')return false;if(!volume(config.prefs(),'effects')){if(force)report('muted');return false;}const request=effectRequest,now=Date.now(),gap=kind.startsWith('footstep')?210:kind==='clock'||kind==='mirror'?70:35;if(!force&&now-(last[kind]||0)<gap)return false;last[kind]=now;try{const buffer=await load(kind);if(request!==effectRequest||paused||!volume(config.prefs(),'effects'))return false;if(voices.size>=12){const oldest=voices.values().next().value;voices.delete(oldest);try{oldest.stop();}catch(_){}}const source=ctx.createBufferSource(),g=ctx.createGain();source.buffer=buffer;g.gain.value=Math.max(0,Math.min(1,gain));source.connect(g);let panner;const location=typeof point==='function'?point():point;if(vector(location)&&ctx.createPanner){panner=ctx.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=Number.isFinite(refDistance)?Math.max(1,refDistance):6;panner.rolloffFactor=1;panner.maxDistance=400;setPosition(panner,location);spatial.set(source,{panner,point});g.connect(panner);panner.connect(effectsBus);updateSpatial();}else if(ctx.createStereoPanner){panner=ctx.createStereoPanner();panner.pan.value=Math.max(-1,Math.min(1,pan));g.connect(panner);panner.connect(effectsBus);}else g.connect(effectsBus);voices.add(source);source.onended=()=>{voices.delete(source);spatial.delete(source);source.disconnect();g.disconnect();panner?.disconnect();};source.start();report('effect-playing');return true;}catch(_){report('missing','audio/'+kind+'.wav');return false;}}
function position(x,z,forced=null){const name=environment(x,z,forced);if(Date.now()>previewUntil&&!festivalLocked)setMusic(name);setAmbience(name);}
function stopVoices(){effectRequest++;for(const source of voices){try{source.stop();}catch(_){}}voices.clear();spatial.clear();}
function stop(){paused=true;musicRequest++;ambientRequest++;loadingMusic=null;loadingAmbient=null;stopVoices();for(const pair of loops)fadeStop(pair,.08);current=null;ambient=null;}
async function suspend(){paused=true;previewUntil=0;musicRequest++;ambientRequest++;loadingMusic=null;loadingAmbient=null;stopVoices();if(ctx)await ctx.suspend().catch(()=>{});}
async function resume(){if(!ctx||!unlocked)return false;paused=false;try{await ctx.resume();}catch(_){report('blocked');return false;}if(ctx.state!=='running'){report('blocked');return false;}gains();ensureLoops();return true;}
function narration(active){duck=active?.25:1;gains();}
function verifyOutput(delay){if(!analyser)return;const request=effectRequest;root.setTimeout(()=>{if(paused||request!==effectRequest)return;if(ctx.state!=='running'){report('blocked');return;}const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);const rms=Math.sqrt(data.reduce((sum,n)=>sum+n*n,0)/data.length);report(rms>.00001?'signal':'silent');},delay);}
async function testMusic(name){if(!await unlock())return false;if(!volume(config.prefs(),'music')){report('muted');return false;}const ok=await setMusic(name,{preview:true});if(ok)verifyOutput(700);return ok;}
async function testEffect(name){if(!await unlock())return false;const ok=await play(name,{force:true});if(ok)verifyOutput(120);return ok;}
function preloadEffects(){if(!ctx)return;Promise.allSettled(EFFECTS.map(name=>load(name))).then(rows=>{if(rows.some(r=>r.status==='rejected'))report('missing');});}
return{unlock,play,setMusic,setAmbience,position,listener,updateSpatial,update(){updateSpatial();gains();ensureLoops();},suspend,resume,narration,testMusic,testEffect,preloadEffects,stop,destroy(){stop();ctx?.close().catch(()=>{});},state(){return{unlocked,paused,context:ctx?.state,music:current?.name,ambience:ambient?.name,voices:voices.size,loops:loops.size};}};
}
const api={create,TRACKS,EFFECTS,AREAS,environment,volume};if(typeof module!=='undefined')module.exports=api;root.MoonAudio=api;
})(typeof window!=='undefined'?window:globalThis);
