/* Original campaign and learning rules. Independent of rendering/storage. */
(function(root){'use strict';
const regions=['bridge','garden','library','clock','lights'];
const names={nl:['Het slapende dorp','Geheimen van het herfstbos','De wandelende tuin','De Maanexpress','Vergeten sterren'],fr:['Le village endormi','Les secrets du bois','Le jardin voyageur','Le Train de la Lune','Les étoiles oubliées']};
const stories={nl:['Lumi heeft een sterrenkaart gevonden. Herstel de eerste lantaarns om haar te lezen.','De kaart wijst naar het bos. Een kleine vos bewaakt een verloren sterrenstuk.','De bloemen verplaatsen zich! Help de tuinier de weg naar de volgende ster te vinden.','De trein kan weer rijden. Zoek de juiste route naar het kasteel.','Alle aanwijzingen komen samen. Wek de maanmachine en bereid het feest voor.'],fr:['Lumi a trouvé une carte céleste. Rallume les lanternes pour la lire.','La carte mène au bois. Un petit renard garde une étoile perdue.','Les fleurs se déplacent ! Aide le jardinier à retrouver le chemin.','Le train peut repartir. Trouve le bon trajet vers le château.','Rassemble les indices. Réveille la machine lunaire et prépare la fête.']};
const layout=[['bridge','groups'],['library','riddle'],['garden','fraction'],['clock','time'],['lights','pattern'],['bridge','sequence'],['bridge','sequence'],['library','word'],['lights','deduction'],['garden','groups'],['clock','time'],['lights','mirror'],['garden','fraction'],['bridge','groups'],['library','word'],['lights','route'],['garden','fraction'],['library','riddle'],['clock','time'],['bridge','sequence'],['garden','groups'],['library','word'],['lights','mirror'],['clock','time'],['lights','deduction'],['garden','fraction'],['library','word'],['clock','time'],['lights','mirror'],['bridge','groups']];
function rngFor(seed){let n=2166136261;for(const c of String(seed))n=Math.imul(n^c.charCodeAt(0),16777619);return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function skill(events,area){const r=events.filter(e=>e.area===area).slice(-5);return r.length>=4&&r.filter(e=>e.attempts===1&&!e.assisted).length>=4?3:r.filter(e=>e.attempts===1&&!e.assisted).length>=2?2:1;}
function make(index,level,lang='nl',seed=0){const E=root.MoonEngine;if(!E)throw Error('MoonEngine required');index=Math.max(0,Math.min(29,index));level=Math.max(1,Math.min(3,level));const [area,type]=layout[index],rng=rngFor(index+':'+level+':'+lang+':'+seed),pick=a=>a[Math.floor(rng()*a.length)],q={index,area,type,level,lang};
if(type==='groups'){Object.assign(q,E.make('bridge',level,lang,rng));q.area=area;}
if(type==='fraction')Object.assign(q,E.make('garden',level,lang,rng));
if(type==='word')Object.assign(q,E.make('library',level,lang,rng));
if(type==='time')Object.assign(q,E.make('clock',level,lang,rng));
if(type==='pattern'||type==='mirror'){Object.assign(q,E.make('lights',type==='pattern'?1:Math.max(2,level),lang,rng));q.level=level;}
if(type==='sequence'){q.step=pick(level===1?[1,2]:level===2?[2,5,10]:[3,4,6,7]);q.start=pick([0,1,2,3])*q.step;q.n=level===1?5:7;q.missing=Math.floor(q.n/2);q.values=Array.from({length:q.n},(_,i)=>q.start+i*q.step);q.answer=q.values[q.missing];q.choices=[q.answer,q.answer+q.step,q.answer-q.step].sort(()=>rng()-.5);}
if(type==='riddle'){const rows=lang==='fr'?[['J’ai des aiguilles, mais je ne pique pas.','horloge','clock'],['J’éclaire la nuit et je change de forme.','lune','moon'],['J’ai des pages, mais je ne suis pas un arbre.','livre','book']]:[['Ik heb wijzers, maar ik prik niet.','klok','clock'],['Ik verlicht de nacht en verander van vorm.','maan','moon'],['Ik heb bladzijden, maar ben geen boom.','boek','book']];const row=rows[(index+seed)%rows.length];q.clue=row[0];q.answer=row[2];q.choices=rows.map(r=>({label:r[1],value:r[2]}));}
if(type==='deduction'){q.choices=lang==='fr'?['Renard','Hibou','Chat']:['Vos','Uil','Kat'];q.answer=pick([0,1,2]);const other=[0,1,2].filter(i=>i!==q.answer);q.clue=lang==='fr'?`${q.choices[other[0]]} porte une lanterne rouge. ${q.choices[other[1]]} porte une lanterne verte. Qui porte la bleue ?`:`${q.choices[other[0]]} draagt een rode lantaarn. ${q.choices[other[1]]} draagt een groene lantaarn. Wie draagt de blauwe?`;}
if(type==='route'){q.target=[2,level===1?1:2];q.moves=level===1?3:4;q.answer='E'.repeat(2)+'N'.repeat(q.target[1]);}
return q;}
function initial(q){if(q.type==='groups')return q.targets.map((_,i)=>i===0?q.initial:0);if(q.type==='fraction')return Array(q.total).fill(null);if(q.type==='word')return[];if(q.type==='time')return 720;if(q.type==='mirror')return[...q.initial];if(q.type==='route')return'';return null;}
function check(q,a){if(q.type==='sequence'||q.type==='riddle'||q.type==='deduction')return a===q.answer;if(q.type==='route'){let x=0,y=0;if(typeof a!=='string'||a.length!==q.moves)return false;for(const c of a){if(c==='E')x++;else if(c==='N')y++;else return false;if(x>2||y>2)return false;}return x===q.target[0]&&y===q.target[1];}if(q.type==='word'){if(!Array.isArray(a))return false;return a.map(id=>q.tiles.find(x=>x.id===id)?.letter||'').join('')===q.word&&new Set(a).size===a.length;}const canonical={groups:'bridge',fraction:'garden',time:'clock',pattern:'lights',mirror:'lights'}[q.type];return canonical?root.MoonEngine.check({...q,area:canonical},a):false;}
function completed(events){return new Set(events.filter(e=>Number.isInteger(e.quest)&&e.quest>=0&&e.quest<30).map(e=>e.quest));}
function next(events){const done=completed(events);for(let i=0;i<30;i++)if(!done.has(i))return i;return 30;}
function chapter(events){return Math.min(4,Math.floor(next(events)/6));}
function validateDraft(d){return d&&d.q&&Number.isInteger(d.q.index)&&d.q.index>=0&&d.q.index<30&&regions.includes(d.q.area)&&[1,2,3].includes(d.q.level)&&typeof d.attempts==='number'&&typeof d.assisted==='boolean';}
const api={regions,names,stories,layout,make,initial,check,skill,completed,next,chapter,validateDraft,rngFor};if(typeof module!=='undefined')module.exports=api;root.MoonCampaign=api;
})(typeof window!=='undefined'?window:globalThis);
