/* Three progressive hints per learning task. Pure: never edits a task or answer. */
(function(root){'use strict';
const text=(lang,nl,fr)=>lang==='fr'?fr:nl;
function stageNumber(value){const number=Number(value);return Number.isNaN(number)?1:Math.max(1,Math.min(3,Math.floor(number||1)));}
function choose(stage,rows){return rows[stageNumber(stage)-1];}
function progressLabel(stage,lang='nl'){const n=stageNumber(stage);return text(lang,`Tip ${n} van 3`,`Indice ${n} sur 3`);}
function time(value){const minutes=((value%1440)+1440)%1440;return `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;}
function family(q){if(q.type)return q.type;return {bridge:'groups',garden:'fraction',library:'word',clock:'time',lights:q.kind==='mirror'?'mirror':'pattern'}[q.area];}
function routePosition(value){let x=0,y=0,valid=true;for(const c of typeof value==='string'?value:''){if(c==='E')x++;else if(c==='W')x--;else if(c==='N')y++;else if(c==='S')y--;else valid=false;if(x<0||x>2||y<0||y>2)valid=false;}return{x,y,valid};}
function routeStepHint(q,answer,lang){
 const path=typeof answer==='string'?answer:'',p=routePosition(path),left=q.moves-path.length,distance=Math.abs(q.target[0]-p.x)+Math.abs(q.target[1]-p.y);
 if(!p.valid||left<distance||(left-distance)%2!==0)return text(lang,`Controleer je laatste stap. Je hebt nog ${Math.max(0,left)} stappen, maar vanaf hier zijn minstens ${distance} nodig. Neem één stap terug en tel opnieuw.`,`Vérifie ton dernier pas. Il te reste ${Math.max(0,left)} pas, mais il en faut au moins ${distance} depuis ici. Annule un pas puis recompte.`);
 if(left===0)return text(lang,'Je hebt alle stappen gebruikt. Vergelijk je laatste vakje met de ster en probeer je route.','Tu as utilisé tous les pas. Compare ta dernière case avec l’étoile, puis essaie ton trajet.');
 if(left===1)return text(lang,'Er blijft één stap over. Zoek welk aangrenzend vakje de ster draagt; kies zelf de richting.','Il reste un pas. Repère la case voisine qui porte l’étoile ; choisis toi-même la direction.');
 const moves=[{x:1,y:0,arrow:'→'},{x:0,y:1,arrow:'↑'},{x:-1,y:0,arrow:'←'},{x:0,y:-1,arrow:'↓'}];
 const next=moves.find(m=>{const x=p.x+m.x,y=p.y+m.y,d=Math.abs(q.target[0]-x)+Math.abs(q.target[1]-y);return x>=0&&x<=2&&y>=0&&y<=2&&d<=left-1&&(left-1-d)%2===0;});
 return next?text(lang,`Vanaf je huidige vakje kun je eerst ${next.arrow} proberen. Er blijven daarna ${left-1} stappen over: plan die zelf en controleer de ster.`,`Depuis ta case actuelle, tu peux d’abord essayer ${next.arrow}. Il restera ${left-1} pas : prépare-les toi-même et vérifie l’étoile.`):text(lang,'Neem één stap terug en vergelijk opnieuw je vakje, de ster en het aantal stappen.','Annule un pas puis compare à nouveau ta case, l’étoile et le nombre de pas.');
}
function exercise(q,answer,stage=1,lang=q?.lang||'nl'){
 q=q||{};lang=lang==='fr'?'fr':'nl';const type=family(q);
 if(type==='groups'){
  const current=Array.isArray(answer)?answer:q.targets.map((_,i)=>i===0?q.initial||0:0),first=q.targets.findIndex((target,i)=>current[i]!==target),i=first<0?0:first,count=Number(current[i])||0,target=q.targets[i];
  const guided=first<0?text(lang,'Tel de eerste mand nog eens vanaf één. Klopt die met het getal? Controleer daarna zelf de andere manden.','Recompte le premier panier depuis un. Correspond-il au nombre ? Vérifie ensuite les autres paniers toi-même.'):text(lang,`Kijk alleen naar mand ${i+1}: er liggen ${count} lichtjes en het doel is ${target}. ${count<target?'Leg er eerst één bij':'Neem er eerst één uit'} en tel opnieuw.`,`Regarde seulement le panier ${i+1} : il contient ${count} lumières pour un objectif de ${target}. ${count<target?'Ajoute d’abord une lumière':'Retire d’abord une lumière'} puis recompte.`);
  return choose(stage,[text(lang,'Kijk naar het getal bij elke mand. Lichtjes die er al liggen tellen ook mee.','Regarde le nombre près de chaque panier. Les lumières déjà présentes comptent aussi.'),text(lang,'Werk één mand tegelijk af: tel wat erin ligt en vergelijk dat met het doel. Ga pas dan naar de volgende.','Termine un panier à la fois : compte son contenu et compare avec l’objectif. Passe ensuite au suivant.'),guided]);
 }
 if(type==='fraction')return choose(stage,[text(lang,'Het onderste getal vertelt in hoeveel gelijke groepjes je alles verdeelt.','Le nombre du bas indique en combien de groupes égaux partager le tout.'),text(lang,`Verdeel de ${q.total} vakjes in ${q.den} even grote groepjes. Het bovenste getal kiest ${q.num} groepje(s) voor blauw.`,`Partage les ${q.total} cases en ${q.den} groupes égaux. Le nombre du haut choisit ${q.num} groupe(s) à colorier en bleu.`),text(lang,`Begin met één vakje in elk van de ${q.den} groepjes. Verdeel de overige ${q.total-q.den} vakjes op dezelfde manier. Tel daarna zelf hoeveel vakjes in de blauwe groepjes zitten.`,`Commence par une case dans chacun des ${q.den} groupes. Répartis les ${q.total-q.den} cases restantes de la même façon. Compte ensuite toi-même les cases des groupes bleus.`)]);
 if(type==='word'){
  const first=Array.from(q.word||'')[0]||'',placed=Array.isArray(answer)?answer.map(id=>q.tiles.find(tile=>tile.id===id)?.letter||'').join(''):typeof answer==='string'?answer:'';
  return choose(stage,[text(lang,'Luister naar de aanwijzing. Welk woord past erbij? Bekijk daarna de losse letters.','Écoute l’indice. Quel mot lui correspond ? Regarde ensuite les lettres séparées.'),text(lang,'Zeg het woord langzaam hardop. Zoek eerst de beginklank en leg de letters van links naar rechts.','Prononce le mot lentement. Cherche d’abord le premier son, puis place les lettres de gauche à droite.'),text(lang,`De eerste letter is « ${first} ». ${placed&&placed[0]!==first?'Neem je eerste letter terug en zoek die letter.':'Zoek of controleer die letter op de eerste plek.'} Spreek daarna zelf de volgende klank uit.`,`La première lettre est « ${first} ». ${placed&&placed[0]!==first?'Annule ta première lettre et cherche celle-ci.':'Trouve ou vérifie cette lettre à la première place.'} Prononce ensuite toi-même le son suivant.`)]);
 }
 if(type==='time'){
  const read=q.kind==='read',back=q.kind==='schedule',step=Math.min(5,Math.max(1,q.duration-1)),partial=q.start+(back?-step:step);
  return choose(stage,[read?text(lang,'Kijk apart naar de korte uurwijzer en de lange minutenwijzer.','Observe séparément la petite aiguille des heures et la grande aiguille des minutes.'):text(lang,back?'Voorbereiden gebeurt vóór het vertrek. Welke kant ga je op in de tijd?':'De reis gebeurt ná het vertrek. Welke kant ga je op in de tijd?',back?'La préparation se fait avant le départ. Dans quel sens faut-il aller dans le temps ?':'Le voyage se fait après le départ. Dans quel sens faut-il aller dans le temps ?'),read?text(lang,'De lange wijzer telt minuten vanaf 12. Elke kleine streep is één minuut; elke grote stap is vijf minuten.','La grande aiguille compte les minutes depuis 12. Chaque petite graduation vaut une minute ; chaque grande graduation en vaut cinq.'):text(lang,`Begin bij ${time(q.start)} en ${back?'trek de voorbereidingstijd af':'tel de reistijd erbij'}. Maak kleine sprongen; let op als je een heel uur passeert.`,`Pars de ${time(q.start)} et ${back?'soustrais la durée de préparation':'ajoute la durée du voyage'}. Avance par petits pas ; attention au passage d’une heure entière.`),read?text(lang,`Werk eerst alleen aan de lange wijzer: tel vanaf 12 tot ${q.start%60} minuten. Kies daarna zelf het juiste uur met de korte wijzer.`,`Travaille d’abord seulement sur la grande aiguille : compte depuis 12 jusqu’à ${q.start%60} minutes. Choisis ensuite toi-même la bonne heure avec la petite aiguille.`):text(lang,`De eerste sprong: ${time(q.start)} ${back?'−':'+'} ${step} minuten = ${time(partial)}. Er blijven ${q.duration-step} minuten over; werk die zelf verder uit.`,`Premier pas : ${time(q.start)} ${back?'−':'+'} ${step} minutes = ${time(partial)}. Il reste ${q.duration-step} minutes ; continue toi-même le calcul.`)]);
 }
 if(type==='sequence'){
  let i=0;while(i<q.values.length-1&&(i===q.missing||i+1===q.missing))i++;
  return choose(stage,[text(lang,'Bekijk de afstand tussen twee getallen die naast elkaar staan.','Observe l’écart entre deux nombres voisins.'),text(lang,'Zoek één vaste sprong tussen de bekende stenen. Controleer of dezelfde sprong ook elders werkt.','Cherche un pas constant entre les pierres connues. Vérifie que ce même pas fonctionne ailleurs.'),text(lang,`Gebruik de bekende stenen ${q.values[i]} en ${q.values[i+1]}: bereken eerst ${q.values[i+1]} − ${q.values[i]}. Maak met die sprong de steen vóór het gat één stap groter.`,`Utilise les pierres connues ${q.values[i]} et ${q.values[i+1]} : calcule d’abord ${q.values[i+1]} − ${q.values[i]}. Ajoute ce pas une fois à la pierre juste avant le trou.`)]);
 }
 if(type==='riddle'){
  const label=q.choices?.find(item=>item.value===q.answer)?.label||'',first=Array.from(label)[0]||'';
  return choose(stage,[text(lang,'Lees het raadsel nog eens. Welke eigenschap valt je het meest op?','Relis l’énigme. Quelle propriété te frappe le plus ?'),text(lang,'Vergelijk elke keuze met alle delen van het raadsel. Een keuze moet bij iedere aanwijzing passen.','Compare chaque choix avec toutes les parties de l’énigme. Il doit correspondre à chaque indice.'),text(lang,`De naam begint met « ${first} ». Zoek een keuze met die beginklank en controleer zelf of alle eigenschappen passen.`,`Le nom commence par « ${first} ». Cherche un choix avec ce premier son et vérifie toi-même toutes ses propriétés.`)]);
 }
 if(type==='deduction'){
  const eliminated=q.choices?.find((_,i)=>i!==q.answer)||'';
  return choose(stage,[text(lang,'Elk genoemd dier heeft al een eigen kleur. Kijk naar de kleur die wordt gevraagd.','Chaque animal cité possède déjà sa couleur. Observe la couleur demandée.'),text(lang,'Streep dieren weg die volgens de aanwijzing een andere kleur dragen. Controleer de twee zinnen apart.','Écarte les animaux qui portent une autre couleur d’après l’indice. Vérifie séparément les deux phrases.'),text(lang,`Je kunt ${eliminated} wegstrepen: dat dier heeft in de aanwijzing al een andere kleur. Onderzoek nu zelf de andere zin.`,`Tu peux écarter ${eliminated} : cet animal porte déjà une autre couleur dans l’indice. Examine maintenant toi-même l’autre phrase.`)]);
 }
 if(type==='route')return choose(stage,[text(lang,'De ster en het aantal stappen zijn allebei belangrijk. Kijk waar je nu staat.','L’étoile et le nombre de pas comptent tous les deux. Observe ta position actuelle.'),text(lang,'Tel de horizontale en verticale afstand. Heb je extra stappen nodig, dan kost heen en terug twee stappen. Blijf binnen het rooster.','Compte la distance horizontale et verticale. Si tu dois ajouter des pas, un aller-retour en coûte deux. Reste dans la grille.'),routeStepHint(q,answer,lang)]);
 if(type==='pattern')return choose(stage,[text(lang,'Zoek een klein groepje dat telkens terugkomt.','Cherche un petit groupe qui revient plusieurs fois.'),text(lang,'Baken één herhaald groepje af. Tel welke plek het gat binnen dat groepje inneemt.','Délimite un groupe qui se répète. Compte la position du trou à l’intérieur de ce groupe.'),text(lang,`Vergelijk de lege plek ${q.missing+1} met plek ${q.missing-q.unit.length+1} in het vorige groepje. Ze hebben dezelfde plek in de herhaling; kies zelf het passende teken.`,`Compare la case vide ${q.missing+1} avec la case ${q.missing-q.unit.length+1} du groupe précédent. Elles occupent la même position dans la répétition ; choisis toi-même le symbole.`)]);
 if(type==='mirror'){
  const first=q.mirrors?.find(m=>m.y===(q.source?.y??1))||q.mirrors?.[0],item=typeof first?.solution==='number'?{type:'mirror',orientation:first.solution}:first?.solution,glyph=item?.orientation===0?'\\':'/';
  return choose(stage,[text(lang,'Volg het licht vanaf de bron. Waar ontmoet de straal het eerste onderdeel?','Suis la lumière depuis la source. Où le rayon rencontre-t-il la première pièce ?'),text(lang,q.optics?'Een spiegel laat de straal een bocht maken. Het splitsprisma maakt ook een tak rechtdoor. Volg elke tak apart.':'Een spiegel laat de straal een bocht maken. Verander één spiegel tegelijk en volg daarna de nieuwe richting.',q.optics?'Un miroir fait tourner le rayon. Le prisme séparateur crée aussi une branche tout droit. Suis chaque branche séparément.':'Un miroir fait tourner le rayon. Modifie un miroir à la fois puis suis sa nouvelle direction.'),text(lang,`Probeer alleen de eerste plek, kolom ${first.x+1}, rij ${first.y+1}: ${item?.type==='splitter'?'een splitsprisma':'een spiegel'} in stand « ${glyph} ». Volg de straal daarna en kies zelf de overige onderdelen.`,`Essaie seulement le premier emplacement, colonne ${first.x+1}, ligne ${first.y+1} : ${item?.type==='splitter'?'un prisme séparateur':'un miroir'} orienté « ${glyph} ». Suis ensuite le rayon et choisis toi-même les autres pièces.`)]);
 }
 return choose(stage,[text(lang,'Bekijk wat de vraag precies vraagt.','Observe ce que demande la question.'),text(lang,'Verdeel de vraag in kleine stappen en controleer één stap tegelijk.','Découpe la question en petites étapes et vérifie-en une à la fois.'),text(lang,'Begin met het eerste voorwerp of de eerste keuze. Controleer dat deel voordat je verdergaat.','Commence par le premier objet ou le premier choix. Vérifie cette partie avant de continuer.')]);
}
function arithmeticHints(task){
 const lang=task.lang,high=task.level>=3,mode=task.operation,numbers=(task.expression.match(/\d+/g)||[]).map(Number),a=numbers[0],b=numbers[1];
 const pause=text(lang,'Je mag stoppen met bewegen terwijl je nadenkt.','Tu peux arrêter de bouger pendant que tu réfléchis.');
 if(mode===3&&!high)return [text(lang,'Kijk naar de grootte van de getallen. '+pause,'Observe la grandeur des nombres. '+pause),text(lang,'Vergelijk eerst de tientallen. Als die gelijk zijn, vergelijk je de eenheden.','Compare d’abord les dizaines. Si elles sont égales, compare les unités.'),text(lang,`Het eerste getal heeft ${Math.floor(a/10)} tiental(len). Zoek zelf de tientallen van het tweede; vergelijk daarna zo nodig de eenheden.`,`Le premier nombre a ${Math.floor(a/10)} dizaine(s). Trouve toi-même les dizaines du second ; compare ensuite les unités si nécessaire.`)];
 if(mode===2)return [text(lang,'Het vraagteken is het ontbrekende deel. '+pause,'Le point d’interrogation représente la partie manquante. '+pause),text(lang,high?'Zoek hoeveel gelijke groepjes van het eerste getal in het totaal passen.':'Tel vanaf het eerste getal door tot het totaal. Het aantal sprongen vult het vraagteken.',high?'Cherche combien de groupes égaux du premier nombre entrent dans le total.':'Compte depuis le premier nombre jusqu’au total. Le nombre de pas remplace le point d’interrogation.'),text(lang,high?`Omcirkel eerst één groepje van ${a} in het totaal ${b}. Tel dat groepje mee en zoek zelf hoeveel gelijke groepjes er nog passen.`:`Begin op ${a} en zet één telstreepje voor je eerste sprong. Tel verder tot ${b}; tel daarna zelf je streepjes.`,high?`Entoure d’abord un groupe de ${a} dans le total ${b}. Compte ce groupe et cherche toi-même combien de groupes égaux peuvent encore entrer.`:`Pars de ${a} et trace un bâton pour ton premier pas. Continue jusqu’à ${b} ; compte ensuite toi-même tes bâtons.`)];
 if(high){
  if(mode===1)return [text(lang,'Het deelteken vraagt om gelijke groepjes. '+pause,'Le signe de division demande des groupes égaux. '+pause),text(lang,'Verdeel het totaal in groepjes met de grootte na het deelteken. Tel hoeveel groepjes je maakt.','Partage le total en groupes de la taille indiquée après le signe de division. Compte les groupes obtenus.'),text(lang,`Begin met één groepje van ${b} uit de ${a}. Leg dat apart. Verdeel de rest zelf op dezelfde manier en tel alle groepjes.`,`Commence par un groupe de ${b} parmi les ${a}. Mets-le de côté. Partage toi-même le reste de la même façon puis compte tous les groupes.`)];
  const guided=mode===0&&b===1?text(lang,'De tweede factor is één. Teken één groepje met evenveel stippen als de eerste factor. Tel zelf de stippen om de poort te kiezen.','Le second facteur est un. Dessine un groupe avec autant de points que le premier facteur. Compte toi-même les points pour choisir la porte.'):text(lang,`Teken eerst één groepje van ${a}. Maak zelf nog ${b-1} gelijke groepjes en tel ze.${mode===0?'':' Bewaar de bewerking buiten de haakjes tot het einde.'}`,`Dessine d’abord un groupe de ${a}. Forme toi-même encore ${b-1} groupes égaux et compte leur contenu.${mode===0?'':' Garde l’opération hors des parenthèses pour la fin.'}`);
  return [text(lang,mode===0?'Het keerteken maakt gelijke groepjes. '+pause:'Werk eerst aan de berekening tussen haakjes. '+pause,mode===0?'Le signe de multiplication forme des groupes égaux. '+pause:'Commence par le calcul entre parenthèses. '+pause),text(lang,mode===0?'Maak zoveel gelijke groepjes als de tweede factor en tel de inhoud.':'Bereken eerst de vermenigvuldiging. Voer pas daarna het plus- of minteken buiten de haakjes uit.',mode===0?'Forme autant de groupes égaux que le second facteur, puis compte leur contenu.':'Calcule d’abord la multiplication. Effectue ensuite seulement l’addition ou la soustraction hors des parenthèses.'),guided];
 }
 const subtract=mode===1||mode===4,step=b>1?1:0,partial=a+(subtract?-step:step);
 return [text(lang,subtract?'Bij min wordt een hoeveelheid kleiner. '+pause:'Bij plus komen hoeveelheden samen. '+pause,subtract?'Avec une soustraction, une quantité diminue. '+pause:'Avec une addition, les quantités se réunissent. '+pause),text(lang,subtract?'Begin bij het eerste getal. Maak naar links zoveel sprongen als het tweede getal.':'Begin bij het eerste getal. Maak naar rechts zoveel sprongen als het tweede getal.',subtract?'Pars du premier nombre. Fais vers la gauche autant de pas que le second nombre.':'Pars du premier nombre. Fais vers la droite autant de pas que le second nombre.'),step?text(lang,`Werk één stap uit: ${a} ${subtract?'−':'+'} 1 = ${partial}. Maak zelf nog ${b-1} sprong(en) in dezelfde richting.`,`Fais un seul pas : ${a} ${subtract?'−':'+'} 1 = ${partial}. Effectue toi-même encore ${b-1} pas dans le même sens.`):text(lang,`Zet je vinger op ${a}. Er is één sprong ${subtract?'naar links':'naar rechts'} nodig. Maak die zelf en lees het getal waarop je landt.`,`Pose ton doigt sur ${a}. Il faut un pas ${subtract?'vers la gauche':'vers la droite'}. Fais-le toi-même et lis le nombre d’arrivée.`)];
}
function mini(task,state={},stage=1){
 task=task||{};state=state||{};const lang=task.lang==='fr'?'fr':'nl';
 if(task.id==='mansion'){
  const correct=task.items.find(item=>item.id===task.solution[0]),color=correct.label.split(' · ')[0];
  return choose(stage,[text(lang,'Een sleutel moet zowel bij de kleur als bij het symbool passen.','Une clé doit correspondre à la couleur et au symbole.'),text(lang,task.level===1?'Zoek eerst de genoemde kleur. Controleer daarna bij die sleutels het genoemde symbool.':'Streep eerst de uitgesloten kleuren weg. Controleer daarna apart de aanwijzing over het symbool.',task.level===1?'Cherche d’abord la couleur indiquée. Vérifie ensuite le symbole des clés de cette couleur.':'Écarte d’abord les couleurs exclues. Vérifie ensuite séparément l’indice sur le symbole.'),text(lang,`Voor de kleur kun je je beperken tot « ${color} ». Daar zijn nog verschillende sleutels: bepaal zelf welk symbool ook past.`,`Pour la couleur, tu peux te limiter à « ${color} ». Il reste plusieurs clés : détermine toi-même quel symbole convient aussi.`)]);
 }
 if(task.id==='potions'){
  const amounts=Array.isArray(state.amounts)?state.amounts:[0,0],first=task.solution.findIndex((goal,i)=>amounts[i]!==goal),i=Math.max(0,first),current=Number(amounts[i])||0;
  const guided=first<0?text(lang,'Controleer eerst de hoeveelheid van het eerste ingrediënt met het recept. Doe daarna zelf dezelfde controle voor het tweede en meng.','Vérifie d’abord la quantité du premier ingrédient avec la recette. Fais ensuite toi-même la même vérification pour le second et mélange.'):text(lang,`Kijk alleen naar ${task.ingredients[i]}: je hebt ${current} lepels. ${current<task.solution[i]?'Voeg eerst één lepel toe':'Neem eerst één lepel terug'} en tel opnieuw. Controleer daarna zelf het recept.`,`Regarde seulement ${task.ingredients[i]} : tu as ${current} cuillères. ${current<task.solution[i]?'Ajoute d’abord une cuillère':'Retire d’abord une cuillère'} puis recompte. Vérifie ensuite toi-même la recette.`);
  return choose(stage,[text(lang,'De twee ingrediënten hebben elk hun eigen hoeveelheid.','Les deux ingrédients ont chacun leur quantité.'),text(lang,'Vergelijk elke teller apart met het recept. Te veel? Neem lepels terug. Te weinig? Voeg lepels toe.','Compare chaque compteur séparément avec la recette. Trop ? Retire des cuillères. Pas assez ? Ajoute-en.'),guided]);
 }
 if(task.id==='garden'||task.id==='railway'){
  const train=task.id==='railway',descending=task.direction==='descending',first=task.items.find(item=>item.id===task.solution[0]),wrong=state.selected?.length&&state.selected[0]!==first.id;
  return choose(stage,[text(lang,train?'Let op de vertrektijd bij elk station.':'Let op de richting: gaan de aantallen omhoog of omlaag?',train?'Observe l’heure de départ de chaque gare.':'Observe le sens : les quantités augmentent-elles ou diminuent-elles ?'),text(lang,train?'Vergelijk eerst de uren, daarna de minuten. Kies steeds de vroegste tijd die nog over is.':descending?'Vergelijk de overgebleven zakjes en kies steeds het grootste aantal.':'Vergelijk de overgebleven zakjes en kies steeds het kleinste aantal.',train?'Compare d’abord les heures, puis les minutes. Choisis chaque fois l’heure la plus tôt parmi celles qui restent.':descending?'Compare les sachets restants et choisis chaque fois la plus grande quantité.':'Compare les sachets restants et choisis chaque fois la plus petite quantité.'),text(lang,`${wrong?'Neem je keuzes terug tot de eerste plek. ':''}De eerste plek is voor « ${first.label} ». Vergelijk daarna zelf de overgebleven ${train?'tijden':'aantallen'}; bouw de rest van de volgorde.`,`${wrong?'Annule tes choix jusqu’à la première place. ':''}La première place revient à « ${first.label} ». Compare ensuite toi-même les ${train?'heures':'quantités'} restantes pour construire la suite.`)]);
 }
 if(task.id==='broom'||task.id==='rally')return choose(stage,arithmeticHints(task));
 return choose(stage,[text(lang,'Bekijk de vraag en de voorwerpen.','Observe la question et les objets.'),text(lang,'Vergelijk één voorwerp tegelijk met de vraag.','Compare un objet à la fois avec la question.'),text(lang,'Begin met één kleine stap en controleer die voor je verdergaat.','Commence par une petite étape et vérifie-la avant de continuer.')]);
}
const api={exercise,mini,progressLabel};root.MoonHints=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
