/* Optional, deterministic learning adventures. No clock, lives or campaign writes. */
(function(root){'use strict';
const Variety=root.MoonVariety||(typeof require==='function'?require('./variety.js'):null);
const text=(lang,nl,fr)=>lang==='fr'?fr:nl;
const catalog={
 mansion:{name:{nl:'Het geheim van het maanlandhuis',fr:'Le secret du manoir lunaire'},description:{nl:'Lees aanwijzingen en vind de juiste sleutel.',fr:'Lis les indices et trouve la bonne clé.'},how:{nl:'Vergelijk beide aanwijzingen en kies een sleutel.',fr:'Compare les deux indices et choisis une clé.'}},
 potions:{name:{nl:'De vriendelijke toverdrank',fr:'La potion bienveillante'},description:{nl:'Meet ingrediënten voor een lichtgevende drank.',fr:'Mesure les ingrédients pour une potion lumineuse.'},how:{nl:'Voeg lepels toe. Je kunt terugnemen, leegmaken en mengen.',fr:'Ajoute des cuillères. Tu peux annuler, vider et mélanger.'}},
 broom:{name:{nl:'Bezemvlucht',fr:'Le vol du balai'},description:{nl:'Vlieg door de ring met het juiste antwoord.',fr:'Traverse l’anneau qui porte la bonne réponse.'},how:{nl:'Schuif links/rechts, vlieg vooruit of achteruit en stijg/daal. Vlieg door je antwoordring.',fr:'Glisse à gauche/droite, avance ou recule et monte/descends. Traverse l’anneau choisi.'}},
 garden:{name:{nl:'De spookjesmoestuin',fr:'Le jardin des petits fantômes'},description:{nl:'Plant zaden in de juiste volgorde.',fr:'Plante les graines dans le bon ordre.'},how:{nl:'Kies een zaadzakje voor elk volgend bed, van klein naar groot.',fr:'Choisis un sachet pour chaque parterre, du plus petit au plus grand.'}},
 railway:{name:{nl:'Het stationsraadsel',fr:'Le mystère des gares'},description:{nl:'Plan de stops van de maanexpress.',fr:'Prépare les arrêts de l’express lunaire.'},how:{nl:'Zet de stations op volgorde van hun vertrektijd. Vertrek daarna.',fr:'Range les gares selon leur heure de départ, puis lance le train.'}},
 rally:{name:{nl:'Pompoenenrally',fr:'Le rallye des citrouilles'},description:{nl:'Rijd je pompoenkart door de juiste poort.',fr:'Conduis ton kart-citrouille vers la bonne porte.'},how:{nl:'Stuur links/rechts en geef gas met vooruit. Rijd door het antwoord.',fr:'Vire à gauche/droite et avance pour accélérer. Traverse la réponse.'}}
};
function rng(seed){let n=(Number(seed)||1)>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
function shuffle(a,random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function make(id,level=1,lang='nl',seed=1,round=0){if(!catalog[id])throw new RangeError('Unknown mini-game');level=Math.max(1,Math.min(3,Math.trunc(Number(level)||1)));lang=lang==='fr'?'fr':'nl';round=Math.max(0,Math.trunc(Number(round)||0));const random=rng((Number(seed)||1)+round*7919+Object.keys(catalog).indexOf(id)*997+level*101),n=max=>1+Math.floor(random()*max),task={id,level,lang,seed,round,name:catalog[id].name[lang],how:catalog[id].how[lang],items:[],solution:[]};
 if(id==='mansion'){
  const palette=[['blauwe','bleue','#81bce8'],['gouden','dorée','#ffcb67'],['groene','verte','#a5d98d'],['paarse','violette','#b293e8'],['oranje','orange','#f8a466'],['witte','blanche','#f7f0df']],symbols=[['maan','lune','☾'],['ster','étoile','★'],['blad','feuille','❧'],['zon','soleil','☀'],['hart','cœur','♥'],['ruit','losange','◆']];
  const colorSet=shuffle(palette,random).slice(0,3),shapeSet=shuffle(symbols,random).slice(0,3),colors=colorSet.map(v=>text(lang,v[0],v[1])),shapes=shapeSet.map(v=>text(lang,v[0],v[1])),color=n(3)-1,shape=n(3)-1;
  task.items=shuffle(Array.from({length:9},(_,i)=>({id:'pick:'+i,label:colors[i%3]+' · '+shapes[Math.floor(i/3)],color:i%3,shape:Math.floor(i/3),hex:colorSet[i%3][2],symbol:shapeSet[Math.floor(i/3)][2]})),random);task.solution=['pick:'+(shape*3+color)];
  const otherColors=colors.filter((_,i)=>i!==color),otherShapes=shapes.filter((_,i)=>i!==shape);
  task.question=level===1?text(lang,`De sleutel is ${colors[color]}. Hij heeft een ${shapes[shape]}. Welke past?`,`La clé est ${colors[color]}. Elle porte une ${shapes[shape]}. Laquelle convient ?`):level===2?text(lang,`De sleutel is niet ${otherColors[0]} en niet ${otherColors[1]}. Hij heeft een ${shapes[shape]}. Welke past?`,`La clé n’est ni ${otherColors[0]} ni ${otherColors[1]}. Elle porte une ${shapes[shape]}. Laquelle convient ?`):text(lang,`De sleutel is niet ${otherColors[0]} en niet ${otherColors[1]}. Het symbool is geen ${otherShapes[0]} en geen ${otherShapes[1]}. Welke past?`,`La clé n’est ni ${otherColors[0]} ni ${otherColors[1]}. Le symbole n’est ni ${otherShapes[0]} ni ${otherShapes[1]}. Laquelle convient ?`);
 }
 if(id==='potions'){task.solution=[n((level+2)*3),n((level+2)*3)];task.question=text(lang,`Recept: ${task.solution[0]} lepels maanwater + ${task.solution[1]} lepels sterpoeder. Maak precies deze drank.`,`Recette : ${task.solution[0]} cuillères d’eau lunaire + ${task.solution[1]} cuillères de poudre d’étoiles. Prépare exactement cette potion.`);task.ingredients=[text(lang,'Maanwater','Eau lunaire'),text(lang,'Sterpoeder','Poudre d’étoiles')];}
 if(id==='garden'||id==='railway'){
  const count=level+2,values=[];let value=id==='garden'?n(8):(6+n(12))*60+(n(4)-1)*15;for(let i=0;i<count;i++){values.push(value);value+=id==='garden'?n(level+2):n(level+2)*15;}
  task.direction=id==='garden'&&level>1&&random()<.5?'descending':'ascending';
  task.items=shuffle(values.map((v,i)=>({id:'pick:'+i,label:id==='garden'?text(lang,`${v} zaden`,`${v} graines`):`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')} · ${text(lang,'Station','Gare')} ${i+1}`,value:v})),random);
  task.solution=values.map((_,i)=>'pick:'+i);if(task.direction==='descending')task.solution.reverse();if(task.direction==='descending')task.how=text(lang,'Kies een zaadzakje voor elk volgend bed, van groot naar klein.','Choisis un sachet pour chaque parterre, du plus grand au plus petit.');task.question=id==='garden'?(task.direction==='ascending'?text(lang,'Herstel de tuin: plant van het minste naar het meeste zaden.','Restaure le jardin : plante du moins au plus de graines.'):text(lang,'Plant nu van het meeste naar het minste zaden.','Plante maintenant du plus au moins de graines.')):text(lang,'De trein volgt de vertrektijden. Plan van vroeg naar laat.','Le train suit les heures de départ. Planifie du plus tôt au plus tard.');
 }
 if(id==='broom'||id==='rally'){
  const a=n(level===1?10:level===2?20:12),b=n(level===1?10:level===2?20:12),mode=((Number(seed)||1)+round+level)%5;let expression,answer;
  if(level<3){if(mode===0){expression=`${a} + ${b}`;answer=a+b;}if(mode===1){expression=`${a+b} − ${b}`;answer=a;}if(mode===2){expression=`${a} + ? = ${a+b}`;answer=b;}if(mode===3){expression=text(lang,`het grootste getal: ${a} of ${b}`,`le plus grand nombre : ${a} ou ${b}`);answer=Math.max(a,b);}if(mode===4){expression=`${Math.max(a,b)} − ${Math.min(a,b)}`;answer=Math.abs(a-b);}}
  else{if(mode===0){expression=`${a} × ${b}`;answer=a*b;}if(mode===1){expression=`${a*b} ÷ ${a}`;answer=b;}if(mode===2){expression=`${a} × ? = ${a*b}`;answer=b;}if(mode===3){expression=`(${a} × ${b}) + ${b}`;answer=a*b+b;}if(mode===4){expression=`(${a} × ${b}) − ${b}`;answer=a*b-b;}}
  const values=shuffle([answer,answer+1,answer===0?2:answer-1],random);task.items=values.map((v,i)=>({id:'pick:'+i,label:String(v),value:v}));task.solution=[task.items.find(i=>i.value===answer).id];task.question=text(lang,`Welke poort geeft ${expression}?`,`Quelle porte donne ${expression} ?`);task.expression=expression;task.operation=mode;
 }

 return task;
}
function check(task,state){if(task.id==='potions')return state.amounts.every((v,i)=>v===task.solution[i]);return state.selected.length===task.solution.length&&state.selected.every((v,i)=>v===task.solution[i]);}
function hint(task){if(task.id==='potions')return text(task.lang,'Tel elke soort apart; het recept blijft zichtbaar.','Compte chaque ingrédient séparément ; la recette reste visible.');if(task.id==='garden'&&task.direction==='descending')return text(task.lang,'Zoek eerst het grootste getal.','Cherche d’abord le plus grand nombre.');if(task.id==='garden'||task.id==='railway')return text(task.lang,'Zoek eerst het kleinste getal of de vroegste tijd.','Cherche d’abord le plus petit nombre ou l’heure la plus tôt.');if(task.id==='mansion')return text(task.lang,'Controleer zowel de kleur als het symbool.','Vérifie la couleur et le symbole.');return text(task.lang,'Reken rustig uit. Stoppen en opnieuw proberen mag altijd.','Calcule tranquillement. Tu peux t’arrêter et réessayer.');}
function choices(task,state){const fr=task.lang==='fr',result=[];if(task.id==='potions'){task.ingredients.forEach((label,i)=>{result.push({id:'add:'+i,label:label+' +',disabled:state.amounts[i]>=20},{id:'remove:'+i,label:label+' −',disabled:state.amounts[i]===0});});}else task.items.forEach(i=>result.push({id:i.id,label:i.label,disabled:state.selected.includes(i.id)}));if(task.id==='garden'||task.id==='railway'||task.id==='potions')result.push({id:'check',label:text(task.lang,task.id==='railway'?'Vertrek':task.id==='potions'?'Mengen':'Controleer',task.id==='railway'?'Départ':task.id==='potions'?'Mélanger':'Vérifier'),disabled:false});result.push({id:'undo',label:fr?'Annuler':'Terug',disabled:state.history.length===0},{id:'reset',label:fr?'Recommencer la manche':'Deze ronde opnieuw',disabled:false},{id:'hint',label:fr?'Indice':'Tip',disabled:false});if(task.id==='broom'||task.id==='rally')result.push({id:'slower',label:fr?'Plus lent':'Langzamer',disabled:false},{id:'faster',label:fr?'Plus vite':'Sneller',disabled:false});return result;}
function create(id,options={}){let round=0,completed=false,feedback='',task=null,recent=Array.isArray(options.recent)?options.recent.slice(-12):[],state={amounts:[0,0],selected:[],history:[]},solved=0;function nextTask(){const fresh=Variety.fresh(seed=>make(id,options.level,options.lang,seed,round),(Number(options.seed)||1)+round*101,recent);task=fresh.task;recent.push(fresh.key);recent=recent.slice(-12);}nextTask();function remember(){state.history.push({amounts:[...state.amounts],selected:[...state.selected]});}function reset(){state={amounts:[0,0],selected:[],history:[]};}function finish(){solved++;feedback=text(task.lang,'Goed gevonden!','Bien trouvé !');if(solved===3){completed=true;return;}round++;nextTask();reset();}function validate(){if(check(task,state))finish();else{feedback=text(task.lang,'Nog niet helemaal. Je kunt aanpassen en opnieuw proberen.','Pas encore tout à fait. Tu peux modifier et réessayer.');if(id==='mansion'||id==='broom'||id==='rally')state.selected=[];}}function action(actionId){if(completed)return snapshot();const choice=choices(task,state).find(c=>c.id===actionId);if(!choice||choice.disabled)return snapshot();feedback='';if(actionId==='hint')feedback=hint(task);else if(actionId==='reset')reset();else if(actionId==='undo'){const previous=state.history.pop();if(previous){state.amounts=previous.amounts;state.selected=previous.selected;}}else if(actionId==='check')validate();else if(actionId.startsWith('add:')||actionId.startsWith('remove:')){remember();const i=Number(actionId.split(':')[1]);state.amounts[i]+=actionId.startsWith('add:')?1:-1;}else if(actionId.startsWith('pick:')){remember();state.selected.push(actionId);if(['mansion','broom','rally'].includes(id))validate();}return snapshot();}function snapshot(){return{id,name:task.name,question:task.question,how:task.how,progress:solved/3,round:round+1,rounds:3,level:task.level,lang:task.lang,seed:options.seed||1,choices:completed?[]:choices(task,state),feedback,completed,amounts:[...state.amounts],selected:[...state.selected],task:JSON.parse(JSON.stringify(task))};}return{action,snapshot,hint:()=>hint(task)};}
const api={catalog,make,create,choices,hint,check};root.MoonMiniGames=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
