/* Original procedural 3D artwork and direct world interactions. Babylon.js Apache-2.0. */
(function(root){'use strict';
function create(canvas,api){const B=root.BABYLON,P=root.MoonPuzzleActions,F=root.MoonCamera,G=root.MoonGraphics,R=root.MoonRailway,A=root.MoonAtmosphere,L=root.MoonLandscape,PUZZLE_LAYER=0x10000000;if(!B||!B.Engine.isSupported())throw Error('WebGL');const engine=new B.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,powerPreference:'high-performance'}),scene=new B.Scene(engine);scene.clearColor=new B.Color4(.065,.105,.18,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.006;scene.fogColor=new B.Color3(.10,.16,.24);scene.collisionsEnabled=true;
const terrainHeight=L.makeHeight(R.track?.samples),worldBounds=L.bounds;
function walkHeight(x,z){return R.stations.some((s,i)=>{const p=R.platform(i),dx=x-p.x,dz=z-p.z;return Math.abs(dx*Math.cos(s.heading)-dz*Math.sin(s.heading))<1.5&&Math.abs(dx*Math.sin(s.heading)+dz*Math.cos(s.heading))<3;})?.25:terrainHeight(x,z);}
const camera=new B.ArcRotateCamera('camera',-Math.PI/2,1.06,14,new B.Vector3(0,2,0),scene);camera.lowerBetaLimit=.45;camera.upperBetaLimit=1.25;camera.lowerRadiusLimit=6;camera.upperRadiusLimit=24;camera.inertia=.55;camera.wheelPrecision=25;camera.attachControl(canvas,true);camera.panningSensibility=0;camera.inputs.removeByType('ArcRotateCameraKeyboardMoveInput');camera.inputs.attached.pointers.buttons=[2];camera.minZ=.2;camera.maxZ=500;camera.checkCollisions=true;camera.collisionRadius=new B.Vector3(.7,.7,.7);
const hemi=new B.HemisphericLight('moonwash',new B.Vector3(0,1,0),scene);hemi.intensity=.75;hemi.diffuse=new B.Color3(.65,.79,1);hemi.groundColor=new B.Color3(.32,.22,.28);const moonLight=new B.DirectionalLight('moonlight',new B.Vector3(-.4,-1,.3),scene);moonLight.position=new B.Vector3(25,40,-30);moonLight.intensity=1.1;moonLight.diffuse=new B.Color3(.91,.85,1);
const shadows=new B.ShadowGenerator(1024,moonLight);shadows.useBlurExponentialShadowMap=true;shadows.blurKernel=12;const glow=new B.GlowLayer('lantern-glow',scene,{mainTextureRatio:.5});glow.intensity=.38;
const pipeline=new B.DefaultRenderingPipeline('moonlight-finish',false,scene,[camera]);pipeline.samples=1;pipeline.fxaaEnabled=true;pipeline.imageProcessingEnabled=true;scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.toneMappingType=B.ImageProcessingConfiguration.TONEMAPPING_ACES;scene.imageProcessingConfiguration.exposure=1.2;scene.imageProcessingConfiguration.contrast=1.08;
const mats={};function material(name,hex,em=0){if(mats[name])return mats[name];const m=new B.StandardMaterial(name,scene);m.diffuseColor=B.Color3.FromHexString(hex);m.specularColor=new B.Color3(.12,.12,.12);if(em)m.emissiveColor=m.diffuseColor.scale(em);mats[name]=m;return m;}
const grass=material('moss','#3d6462'),stone=material('stone','#738793'),path=material('warm-path','#a3947f'),wood=material('wood','#715640'),roof=material('roof','#654b70'),plaster=material('plaster','#d5bd99'),gold=material('gold','#edbc67'),dark=material('dark','#273345'),warm=material('warm-light','#ffcc72',1.4),blue=material('moon-drop','#86dbe3',.7),pink=material('red-drop','#dd8ca3',.5),ghostMat=material('Lumi','#c4e7f5',.5),coatMat=material('coat','#4caaaa'),skinMat=material('skin','#d7aa86'),hair=material('hair','#523f48');
// Original tiling surface details; modest canvas textures remain available offline.
let detailRng=root.MoonCampaign.rngFor('material-detail');
function surface(mat,name,base,ink,kind,repeat){
 const texture=new B.DynamicTexture(name,{width:256,height:256},scene,true),c=texture.getContext();c.fillStyle=base;c.fillRect(0,0,256,256);
 if(kind==='wood'){for(let i=0;i<100;i++){c.strokeStyle=i%3?ink:'#a5875b44';c.lineWidth=.5+detailRng();const y=detailRng()*256;c.beginPath();c.moveTo(0,y);for(let x=0;x<=256;x+=16)c.lineTo(x,y+Math.sin(x*.045+i)*2);c.stroke();}}
 else{for(let i=0;i<2200;i++){c.globalAlpha=.12+detailRng()*.15;c.fillStyle=i%2?ink:'#fff3db';c.fillRect(detailRng()*256,detailRng()*256,1+detailRng()*3,1+detailRng()*2);}c.globalAlpha=1;if(kind==='stone'){c.strokeStyle=ink;c.lineWidth=2;for(let y=0;y<256;y+=64){c.beginPath();c.moveTo(0,y);c.lineTo(256,y);c.stroke();for(let x=(y/64%2)*64;x<256;x+=128){c.beginPath();c.moveTo(x,y);c.lineTo(x,y+64);c.stroke();}}}}
 texture.update();texture.uScale=texture.vScale=repeat;texture.anisotropicFilteringLevel=4;mat.diffuseTexture=texture;mat.diffuseColor=B.Color3.White();
}
surface(wood,'timber-grain','#715640','#47372d','wood',2);surface(stone,'moonstone-blocks','#738793','#435463','stone',3);surface(plaster,'warm-plaster','#d5bd99','#ab967c','noise',2);surface(roof,'roof-detail','#654b70','#40394e','stone',3);
gold.specularColor=new B.Color3(.55,.38,.16);gold.specularPower=48;

let allStatic=[],obstacles=[];function mesh(kind,name,opt,pos,mat,parent=null){let m=B.MeshBuilder[kind](name,opt,scene);m.position=new B.Vector3(...pos);m.material=mat;if(parent){m.parent=parent;if(parent.name==='puzzle'||parent.layerMask===PUZZLE_LAYER)m.layerMask=PUZZLE_LAYER;}m.isPickable=false;if(kind!=='CreatePlane'){m.receiveShadows=true;if(m.layerMask!==PUZZLE_LAYER)allStatic.push(m);}return m;}
const box=(n,p,s,m,parent)=>mesh('CreateBox',n,{width:s[0],height:s[1],depth:s[2]},p,m,parent),ball=(n,p,s,m,parent)=>mesh('CreateSphere',n,{diameter:1,segments:['autumn-crown','pumpkin','head','hair','ghost-body','mushroom-cap','moon'].includes(n)?24:12},p,m,parent);function ell(n,p,s,m,parent){const o=ball(n,p,s,m,parent);o.scaling=new B.Vector3(...s);return o;}function cyl(n,p,h,d,m,parent,top=d){return mesh('CreateCylinder',n,{height:h,diameter:d,diameterTop:top,tessellation:24},p,m,parent);}
function label(text,pos,width=3,parent=null){const tx=new B.DynamicTexture('letter-'+text,{width:512,height:128},scene,false);tx.hasAlpha=true;const c=tx.getContext();c.font='bold 60px sans-serif';const font=Math.min(60,Math.floor(60*490/Math.max(1,c.measureText(text).width)));tx.drawText(text,null,88,'bold '+font+'px sans-serif','#fff3d4','#172b3bea',true);const mat=new B.StandardMaterial('label-'+text,scene);mat.diffuseTexture=tx;mat.emissiveColor=B.Color3.White();mat.disableLighting=true;mat.backFaceCulling=false;const m=mesh('CreatePlane','label',{width,height:width/4},pos,mat,parent);return m;}
function textTop(text,pos,size=1,parent){const tx=new B.DynamicTexture('tile-'+text,{width:256,height:256},scene,false);tx.drawText(String(text),null,165,'bold 120px sans-serif','#fff3d4','#31485d',true);const mat=new B.StandardMaterial('tile-text',scene);mat.diffuseTexture=tx;mat.emissiveColor=new B.Color3(.4,.4,.4);const m=mesh('CreatePlane','tile-label',{size},pos,mat,parent);m.rotation.x=Math.PI/2;return m;}
const skyTexture=new B.DynamicTexture('twilight-gradient',{width:32,height:512},scene,false),skyContext=skyTexture.getContext(),skyGradient=skyContext.createLinearGradient(0,0,0,512);skyGradient.addColorStop(0,'#080f26');skyGradient.addColorStop(.45,'#16243f');skyGradient.addColorStop(.72,'#3c4259');skyGradient.addColorStop(1,'#182a36');skyContext.fillStyle=skyGradient;skyContext.fillRect(0,0,32,512);skyTexture.update();const skyMaterial=new B.StandardMaterial('twilight',scene);skyMaterial.emissiveTexture=skyTexture;skyMaterial.emissiveColor=B.Color3.White();skyMaterial.diffuseColor=B.Color3.Black();skyMaterial.disableLighting=true;skyMaterial.backFaceCulling=false;skyMaterial.fogEnabled=false;const sky=mesh('CreateSphere','twilight-sky',{diameter:420,segments:24},[0,0,0],skyMaterial);sky.infiniteDistance=true;sky.receiveShadows=false;sky.isPickable=false;
const ground=mesh('CreateGround','earth',{width:280,height:280,subdivisions:112,updatable:true},[0,0,25],grass);ground.layerMask|=PUZZLE_LAYER;const positions=ground.getVerticesData(B.VertexBuffer.PositionKind),indices=ground.getIndices(),normals=[];for(let i=0;i<positions.length;i+=3)positions[i+1]=terrainHeight(positions[i],positions[i+2]+25);B.VertexData.ComputeNormals(positions,indices,normals);ground.updateVerticesData(B.VertexBuffer.PositionKind,positions);ground.updateVerticesData(B.VertexBuffer.NormalKind,normals);ground.refreshBoundingInfo();const gt=new B.DynamicTexture('moss-texture',{width:512,height:512},scene,false),ctx=gt.getContext();ctx.fillStyle='#416763';ctx.fillRect(0,0,512,512);let rng=root.MoonCampaign.rngFor('world');for(let i=0;i<3500;i++){ctx.fillStyle=['#385854','#4b7065','#5f7664','#876d57'][Math.floor(rng()*4)];ctx.fillRect(rng()*512,rng()*512,2,2);}gt.update();grass.diffuseTexture=gt;grass.diffuseColor=B.Color3.White();gt.uScale=20;gt.vScale=20;
const waterMat=material('stream','#4d9aa6',.08);waterMat.alpha=.78;waterMat.specularColor=new B.Color3(.6,.8,1);const stream=box('stream',[-9,.025,0],[5,.08,85],waterMat);const waterRipples=[];for(let i=0;i<22;i++){const r=mesh('CreateTorus','ripple',{diameter:1.5,thickness:.018,tessellation:24},[-9+(rng()-.5)*3,.09,-35+i*3.3],blue);waterRipples.push(r);}
const creekDX=L.sites.bridge.x-L.oldSites.bridge.x,creekDZ=L.sites.bridge.z-L.oldSites.bridge.z;stream.position.x+=creekDX;stream.position.z+=creekDZ;stream.scaling.z=2.4;waterRipples.forEach(r=>{r.position.x+=creekDX;r.position.z+=creekDZ;});
const restoredBridge=[];for(let i=0;i<6;i++){const plank=box('bridge-plank',[-11+i*.8,.24,-5.6],[.72,.24,3],wood);plank.setEnabled(false);plank.position.x+=creekDX;plank.position.z+=creekDZ;restoredBridge.push(plank);}const celebrationStars=[];for(let i=0;i<5;i++){const star=ell('constellation-star',[(i-2)*1.5,10+Math.sin(i)*.8,45],[.45,.45,.45],warm);star.setEnabled(false);celebrationStars.push(star);}
const sites=L.sites;
function district(area,build){const from=allStatic.length,before=obstacles.length,dx=sites[area].x-L.oldSites[area].x,dz=sites[area].z-L.oldSites[area].z;build();allStatic.slice(from).filter(m=>!m.parent).forEach(m=>{m.position.x+=dx;m.position.z+=dz;});obstacles.slice(before).forEach(o=>{o.x+=dx;o.z+=dz;});}
function road(x,z){const distance=Math.hypot(x,z),count=Math.ceil(distance/3.5);for(let i=0;i<=count;i++){let t=i/count;const m=cyl('path',[x*t,.03,z*t],.06,3.9,path);m.rotation.y=rng();}}
Object.values(sites).forEach(p=>road(p.x,p.z));cyl('village-square',[0,.04,0],.08,13,path);
function pumpkin(x,z,scale=1,parent=null){const y=scale*.42;const p=new B.TransformNode('pumpkin',scene);p.position=new B.Vector3(x,0,z);if(parent)p.parent=parent;ell('pumpkin',[0,y,0],[scale,scale*.8,scale],material('pumpkin','#d88739'),p);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ell('rib',[Math.sin(a)*scale*.19,y,Math.cos(a)*scale*.19],[scale*.5,scale*.76,scale*.5],material('pumpkin-gold','#e5a244'),p);}cyl('stem',[0,scale*.9,0],scale*.22,scale*.14,wood,p);ell('eye',[-scale*.17,y+scale*.1,-scale*.45],[scale*.1,scale*.12,scale*.05],warm,p);ell('eye',[scale*.17,y+scale*.1,-scale*.45],[scale*.1,scale*.12,scale*.05],warm,p);box('smile',[0,y-scale*.13,-scale*.46],[scale*.22,scale*.05,.04],dark,p);return p;}
function tree(x,z,size=1,colour=0){const base=terrainHeight(x,z),from=allStatic.length;obstacles.push({x,z,w:.9*size,d:.9*size});const trunk=cyl('tree',[x,2*size,z],4*size,.65*size,wood,null,.42*size);trunk.rotation.z=(rng()-.5)*.1;const colors=['#b8794e','#d39d56','#b7736d','#617f75'];for(let i=0;i<3;i++)ell('autumn-crown',[x+(i-1)*1.2*size,(4.3+i*.65)*size,z+(i%2)*.5],[3.7*size,2.6*size,3.5*size],material('foliage'+colour,colors[colour]));allStatic.slice(from).forEach(m=>m.position.y+=base);}
for(let i=0;i<100;i++){const x=(rng()-.5)*245,z=(rng()-.3)*220;if(Math.abs(x)<7||(Math.abs(x-12)<6&&z>-7&&z<35)||R.track.samples.some(p=>Math.hypot(x-p.x,z-p.z)<6)||Object.values(sites).some(p=>Math.hypot(x-p.x,z-p.z)<14||L.distance(x,z,{x:0,z:0},p)<4.5))continue;tree(x,z,.65+rng()*.7,Math.floor(rng()*4));}
function cottage(x,z,s=1){x*=L.scale;z*=L.scale;obstacles.push({x,z,w:5*s+.5,d:4*s+.5});box('cottage',[x,1.8*s,z],[5*s,3.6*s,4*s],plaster);const r=cyl('roof',[x,4.25*s,z],2.3*s,7.5*s,roof,null,0);r.rotation.y=Math.PI/4;r.scaling.z=.9;box('door',[x,1.1*s,z-2.03*s],[1.1*s,2.2*s,.12],wood);for(const dx of [-1.55,1.55]){box('window',[x+dx*s,2*s,z-2.08*s],[.95*s,1.1*s,.1],warm);box('window-bar',[x+dx*s,2*s,z-2.15*s],[.07,1.2*s,.1],wood);}box('chimney',[x+1.5*s,4.7*s,z+.4*s],[.65*s,2*s,.8*s],stone);}
cottage(-5,-12,.8);cottage(5,-10,.9);cottage(-4,11,.8);cottage(7,10,.7);cottage(-20,25,1.2);
// Garden glasshouse, beds and luminous plants.
const flowers=[];district('garden',()=>{
obstacles.push({x:22,z:-19,w:8.5,d:6.5});
const glass=material('glass','#97d9cb',.12);glass.alpha=.4;box('greenhouse',[22,2,-19],[8,4,6],glass);for(let x=18;x<=26;x+=2)box('frame',[x,2,-22],[.12,4,.15],gold);for(let z=-22;z<=-16;z+=2)box('frame',[18,2,z],[.12,4,.15],gold);for(let i=0;i<18;i++){const x=13+(i%6)*2,z=-18+Math.floor(i/6)*2;box('garden-bed',[x,.2,z],[1.8,.3,1.6],wood);cyl('stem',[x,.9,z],1.3,.08,grass);const flower=ell('moonflower',[x,1.6,z],[.8,.4,.8],material('flower'+i%3,['#bc8ecc','#e6b28c','#9bd2cb'][i%3],.25));flowers.push(flower);}
});
// Tall moon clock and railway.
let towerHands;district('clock',()=>{obstacles.push({x:21,z:27,w:5,d:5});
cyl('tower',[21,5.5,27],11,4.5,stone);cyl('tower-roof',[21,12,27],3,6,roof,null,0);const clockFace=cyl('tower-clock',[21,8,24.65],.2,3,plaster);clockFace.rotation.x=Math.PI/2;towerHands=[box('hour-hand',[21,8.3,24.45],[.12,.9,.08],dark),box('minute-hand',[21.6,8,24.43],[1.3,.09,.08],dark)];for(let i=0;i<12;i++){const a=i*Math.PI/6;ell('hour-marker',[21+Math.sin(a)*1.22,8+Math.cos(a)*1.22,24.42],[.1,.1,.06],gold);}
});
// Two continuous curved rails, with instanced sleepers along the full loop.
const railPaths=[-1,1].map(side=>R.track.samples.map(p=>new B.Vector3(p.x+Math.cos(p.heading)*side,.19,p.z-Math.sin(p.heading)*side)));
railPaths.forEach((path,i)=>mesh('CreateTube','curved-rail-'+i,{path,radius:.065,tessellation:6},[0,0,0],stone));
const tie=box('rail-tie',[12,.09,0],[3,.12,.4],wood);
for(let d=0;d<R.track.length;d+=1.6){const pose=R.track.pose(d),m=d===0?tie:tie.createInstance('rail-tie');m.position.set(pose.x,.09,pose.z);m.rotation.y=pose.heading;if(d!==0)allStatic.push(m);m.isPickable=false;}
for(const [i,station]of R.stations.entries()){
 const stationRoot=new B.TransformNode('station-'+station.id,scene);stationRoot.position.set(station.x,0,station.z);stationRoot.rotation.y=station.heading;
 box('station-platform',[-4,.12,0],[3,.25,6],stone,stationRoot);box('platform-edge',[-2.55,.28,0],[.12,.08,6],gold,stationRoot);
 for(const dz of [-2.4,2.4])box('station-post',[-5,1.6,dz],[.18,3,.18],wood,stationRoot);
 box('station-canopy',[-4.3,3.15,0],[3.8,.2,6.5],roof,stationRoot);label(station.name.nl+' / '+station.name.fr,[-4.5,2.5,0],4,stationRoot);
 for(let step=0;step<3;step++)box('boarding-step',[-2.2+step*.4,.13+step*.16,0],[.45,.18,1.2],wood,stationRoot);
 const bell=cyl('station-call-bell',[-4,1.1,2],.45,.45,gold,stationRoot);bell.isPickable=true;bell.metadata={station:i,use:()=>callTrain(i)};
 const platform=R.platform(i),site=station.id==='centre'?{x:0,z:0}:sites[station.id],n=Math.ceil(Math.hypot(platform.x-site.x,platform.z-site.z)/2.5);
 for(let j=0;j<=n;j++)cyl('station-path',[site.x+(platform.x-site.x)*j/n,.03,site.z+(platform.z-site.z)*j/n],.06,3.9,path);
}
const train=new B.TransformNode('moon-express',scene);train.position=new B.Vector3(R.stations[0].x,0,R.stations[0].z);
const trainMat=material('train','#607999'),wheels=[];
box('carriage-floor',[0,.6,0],[2.4,.22,4],wood,train);box('carriage-roof',[0,2.8,0],[2.7,.22,4.5],roof,train);
// Open windows and a left doorway leave a clear view from the passenger seat.
for(const x of [-1.15,1.15]){for(const z of [-1.85,1.85])box('carriage-pillar',[x,1.7,z],[.12,2.1,.12],gold,train);
 for(const z of [-1.35,1.35])box('carriage-side',[x,.98,z],[.12,.55,1],trainMat,train);}
for(const z of [-1.95,1.95]){box('carriage-end',[0,.95,z],[2.3,.5,.12],trainMat,train);box('carriage-window-bar',[0,2.6,z],[2.3,.12,.12],gold,train);}
box('passenger-seat',[0,.85,.35],[1.3,.25,1],trainMat,train);box('seat-back',[0,1.25,-.2],[1.3,.8,.15],trainMat,train);
for(const x of [-1,1])for(const z of [-1.2,1.2]){const wheel=cyl('wheel',[x,.55,z],.22,.64,dark,train);wheel.rotationQuaternion=B.Quaternion.RotationAxis(B.Vector3.Forward(),Math.PI/2);wheel.metadata={roll:0};wheels.push(wheel);box('wheel-spoke',[0,0,0],[.5,.08,.08],gold,wheel);}
pumpkin(0,1.05, .45,train);
const railMotion=R.create(),rideCamera=new B.UniversalCamera('train-first-person',new B.Vector3(0,2.05,-.35),scene);rideCamera.minZ=.08;rideCamera.maxZ=500;rideCamera.fov=.9;rideCamera.parent=train;rideCamera.inputs.clear();pipeline.addCamera(rideCamera);
// Friendly castle and observatory.
let moonMachine;district('lights',()=>{obstacles.push({x:0,z:49,w:14,d:6.5});
box('castle',[0,4,49],[11,8,6],stone);for(const x of [-6,6]){cyl('castle-tower',[x,5,49],10,3,stone);cyl('spire',[x,11,49],4,4,roof,null,0);}box('castle-door',[0,1.9,45.9],[2.5,3.8,.15],wood);for(const x of [-3.5,3.5])for(const y of [3,6])box('castle-window',[x,y,45.9],[1,1.4,.15],warm);moonMachine=mesh('CreateTorus','moon-machine',{diameter:4,thickness:.16,tessellation:40},[0,9,48],gold);moonMachine.rotation.x=Math.PI/2;
});
const moon=ell('moon',[18,39,66],[9,9,1],material('moon','#f1e6ba',1));const stars=[];for(let i=0;i<100;i++){const a=rng()*Math.PI*2,dist=160+rng()*25;stars.push(ell('star',[Math.sin(a)*dist,60+rng()*70,Math.cos(a)*dist],[.09,.09,.09],material('star','#dde6f7',1)));}
const lanterns={},siteLabels={};for(const [area,p]of Object.entries(sites)){cyl('lantern-post',[p.x,1.7,p.z],3.4,.18,wood);box('lantern-frame',[p.x,3.2,p.z],[.8,1,.8],gold);const light=ell('lantern-light',[p.x,3.2,p.z],[.5,.65,.5],warm);lanterns[area]=light;siteLabels[area]=label(area,[p.x,4.5,p.z],4);pumpkin(p.x-1.4,p.z,1);pumpkin(p.x+1.3,p.z+.8,.7);}
for(let i=0;i<20;i++){const a=i*Math.PI*2/20;pumpkin(Math.sin(a)*6,Math.cos(a)*6,.45+rng()*.4);}
for(let i=0;i<22;i++){const x=(rng()-.5)*155,z=rng()*135-45,from=allStatic.length;if(Object.values(sites).some(p=>Math.hypot(x-p.x,z-p.z)<6))continue;cyl('mushroom',[x,.4,z],.8,.2,plaster);ell('mushroom-cap',[x,.85,z],[.9,.35,.9],material('mushroom','#9a6680'));allStatic.slice(from).forEach(m=>m.position.y+=terrainHeight(x,z));}
// Hero: articulated limbs, lantern, face and scarf.
const hero=new B.TransformNode('explorer',scene);hero.position=new B.Vector3(0,0,-3);const body=cyl('coat',[0,1.2,0],1.1,.8,coatMat,hero,.6);ell('head',[0,2.08,0],[.7,.78,.65],skinMat,hero);ell('hair',[0,2.38,.035],[.76,.38,.69],hair,hero);ell('eye',[-.13,2.1,-.3],[.06,.09,.04],dark,hero);ell('eye',[.13,2.1,-.3],[.06,.09,.04],dark,hero);box('smile',[0,1.93,-.32],[.13,.025,.02],dark,hero);const hat=cyl('hat',[0,2.52,0],.4,.8,coatMat,hero,.15);cyl('hat-brim',[0,2.36,0],.08,1.05,coatMat,hero);box('scarf',[0,1.76,-.02],[.75,.15,.65],gold,hero);box('scarf-end',[.2,1.5,-.4],[.18,.55,.08],gold,hero);
const limbs=[];for(const x of [-.25,.25]){const leg=new B.TransformNode('leg',scene);leg.parent=hero;leg.position.set(x,.8,0);cyl('leg',[0,-.28,0],.6,.24,dark,leg);box('boot',[0,-.65,-.09],[.29,.25,.44],wood,leg);limbs.push(leg);}for(const x of [-.47,.47]){const arm=new B.TransformNode('arm',scene);arm.parent=hero;arm.position.set(x,1.6,0);cyl('sleeve',[0,-.25,0],.6,.23,coatMat,arm);ell('hand',[0,-.57,0],[.22,.24,.23],skinMat,arm);limbs.push(arm);}box('held-lantern',[.53,.8,-.1],[.3,.4,.3],warm,hero);const heroLight=new B.PointLight('hero-lantern',new B.Vector3(.5,1,-.3),scene);heroLight.parent=hero;heroLight.diffuse=new B.Color3(1,.74,.37);heroLight.intensity=.5;heroLight.range=6;
const ghost=new B.TransformNode('Lumi',scene);ell('ghost-body',[0,0,0],[.85,1.15,.7],ghostMat,ghost);ell('ghost-eye',[-.15,.13,-.33],[.07,.12,.04],dark,ghost);ell('ghost-eye',[.15,.13,-.33],[.07,.12,.04],dark,ghost);ell('ghost-cheek',[-.23,-.07,-.31],[.14,.07,.04],pink,ghost);ell('ghost-cheek',[.23,-.07,-.31],[.14,.07,.04],pink,ghost);cyl('ghost-hat',[0,.75,0],.65,.65,roof,ghost,0);cyl('ghost-brim',[0,.45,0],.06,.95,roof,ghost);
// Distant low-poly silhouettes are decorative; the playable ground remains gentle.
for(let i=0;i<14;i++){const a=i*Math.PI*2/14,x=Math.sin(a)*170,z=25+Math.cos(a)*180;const mountain=cyl('distant-mountain',[x,10+i%4*3,z],24+i%4*6,35+i%3*9,material('mountain'+i%3,['#425367','#536071','#65707c'][i%3]),null,0);mountain.rotation.y=i*.7;}
const fireflies=[];for(let i=0;i<35;i++)fireflies.push(ell('firefly',[(rng()-.5)*55,1+rng()*3,rng()*60-15],[.09,.09,.09],warm));
allStatic.forEach(m=>{if(['cottage','roof','castle','castle-tower','tower','greenhouse','tree'].includes(m.name))m.checkCollisions=true;if(!m.parent&&m!==sky&&m!==moonMachine&&m!==moon&&!flowers.includes(m)&&!fireflies.includes(m)&&!waterRipples.includes(m)&&!Object.values(lanterns).includes(m))m.freezeWorldMatrix();});[body,...hero.getChildMeshes(),...train.getChildMeshes()].forEach(m=>shadows.addShadowCaster(m));
const beacon=mesh('CreateTorus','quest-beacon',{diameter:1.8,thickness:.09,tessellation:32},[0,5,0],warm);beacon.rotation.x=Math.PI/2;allStatic.filter(m=>m.name==='cottage'||m.name==='roof'||m.name==='autumn-crown'||m.name==='castle').forEach(m=>shadows.addShadowCaster(m));
// Bounded effects pools: no new geometry in the render loop.
const atmosphere=A.create(),sun=ell('sun',[0,35,70],[6,6,1],material('sun','#ffd595',1));
moon.material.fogEnabled=false;sun.material.fogEnabled=false;mats.star.fogEnabled=false;
const dustMat=material('walking-dust','#d9ba8c',.15);dustMat.alpha=.4;
const mistMat=material('train-mist','#ccd9e7',.25);mistMat.alpha=.3;
const leafMat=material('wind-leaf','#d89358');
const dust=Array.from({length:12},()=>{const m=ell('walking-dust',[0,0,0],[.1,.1,.1],dustMat);m.setEnabled(false);return{m,life:0};});
const steam=Array.from({length:8},()=>{const m=ell('train-mist',[0,0,0],[.3,.3,.3],mistMat);m.setEnabled(false);return{m,life:0};});
const leaves=Array.from({length:12},(_,i)=>{const m=box('wind-leaf',[0,0,0],[.13,.025,.22],leafMat);m.setEnabled(false);return m;});
const wisp=ell('wandering-wisp',[0,0,0],[.55,.8,.55],material('wandering-wisp','#bde1eb',.5));wisp.material.alpha=.5;wisp.setEnabled(false);
const boltMat=material('distant-lightning','#cad8f2',.7);const bolt=mesh('CreateLines','distant-lightning',{points:[new B.Vector3(30,56,68),new B.Vector3(28,49,68),new B.Vector3(31,49,68),new B.Vector3(26,40,68)]},[0,0,0],boltMat);bolt.color=new B.Color3(.65,.73,.88);bolt.setEnabled(false);
let lastDustPosition=hero.position.clone(),dustCursor=0,steamCursor=0,dustClock=0,steamClock=0,boltLife=0,skyClock=3,lastSkyDay=-1,lastWeatherLabel='';
function weatherTick(dt){
 const reduced=!!prefs().motion,active=started&&mode!=='puzzle',s=atmosphere.tick(dt,{active,reduced});
 const colour=(night,day)=>B.Color3.Lerp(B.Color3.FromHexString(night),B.Color3.FromHexString(day),s.day);
 // Puzzles retain the original, steady wash and have no weather haze.
 scene.fogDensity=mode==='puzzle'?0:s.fogDensity;
 scene.fogColor=colour('#1a293d','#9da9ad');
 hemi.intensity=mode==='puzzle'?.75:.62+s.day*.3;
 hemi.diffuse=mode==='puzzle'?new B.Color3(.65,.79,1):colour('#a6caff','#ffe5c0');
 moonLight.intensity=mode==='puzzle'?1.1:.85+s.day*.25;
 moonLight.diffuse=mode==='puzzle'?new B.Color3(.91,.85,1):colour('#e8d9ff','#ffe0b1');
 const lightAngle=s.day>.5?s.angle:s.angle+Math.PI;moonLight.direction=mode==='puzzle'?new B.Vector3(-.4,-1,.3):new B.Vector3(-Math.cos(lightAngle)*.5,-Math.max(.45,Math.abs(Math.sin(lightAngle))),-.4).normalize();
 sun.position.set(Math.cos(s.angle)*150,Math.sin(s.angle)*100,135);
 moon.position.set(-Math.cos(s.angle)*150,-Math.sin(s.angle)*100,135);
 sun.visibility=s.day;moon.visibility=1-s.day;stars.forEach(m=>m.visibility=1-s.day);
 skyClock+=dt;if(skyClock>2&&Math.abs(s.day-lastSkyDay)>.01){skyClock=0;lastSkyDay=s.day;const grad=skyContext.createLinearGradient(0,0,0,512);[[0,'#080f26','#537da0'],[.45,'#16243f','#8db2c5'],[.72,'#3c4259','#d3baa1'],[1,'#182a36','#779b9f']].forEach(([at,n,d])=>grad.addColorStop(at,colour(n,d).toHexString()));skyContext.fillStyle=grad;skyContext.fillRect(0,0,32,512);skyTexture.update();}
 const label=s.period+'/'+s.weather+'/'+api.lang();if(label!==lastWeatherLabel){lastWeatherLabel=label;api.atmosphere?.(s);}
 boltLife=s.bolt?.22:Math.max(0,boltLife-dt);bolt.setEnabled(active&&!reduced&&boltLife>0);bolt.visibility=boltLife/.22;if(active&&!reduced)hemi.intensity+=boltLife*.25;
 if(s.thunder)api.effect('thunder',{gain:.24,pan:.35});
 const optional=active&&!reduced,budget=qualityTier==='low'?5:12;
 leaves.forEach((m,i)=>{m.setEnabled(optional&&i<budget);if(optional&&i<budget){const t=s.elapsed*.35+i*.91;m.position.set(hero.getAbsolutePosition().x+Math.sin(t)*7,1+((i*.43-s.elapsed*.3)%4+4)%4,hero.getAbsolutePosition().z+Math.cos(t*.7)*7);m.rotation.set(t*.7,t,t*.3);}});
 wisp.setEnabled(optional&&s.wisp);if(optional&&s.wisp){const u=(s.elapsed%75-55)/10;wisp.visibility=Math.sin(u*Math.PI)*.55;wisp.position.set(hero.getAbsolutePosition().x+8+u*4,2+Math.sin(u*Math.PI)*.5,hero.getAbsolutePosition().z+5);}
 function advance(pool){pool.forEach(p=>{p.life=Math.max(0,p.life-dt);p.m.setEnabled(optional&&p.life>0);if(p.life>0&&optional){p.m.position.y+=dt*.4;p.m.visibility=p.life;const scale=.6+(1-p.life)*1.8;p.m.scaling.setAll(scale*(pool===dust ? .12 : .4));}});}
 advance(dust);advance(steam);
 if(!optional){dustClock=steamClock=0;dust.forEach(p=>p.life=0);steam.forEach(p=>p.life=0);return;}
 dustClock+=dt;steamClock+=dt;
 const walked=B.Vector3.DistanceSquared(lastDustPosition,hero.getAbsolutePosition());lastDustPosition.copyFrom(hero.getAbsolutePosition());
 if(mode==='world'&&moving&&walked>.000001&&walked<1&&dustClock>.16){dustClock=0;const p=dust[dustCursor++%dust.length];p.life=1;p.m.position.copyFrom(hero.position);p.m.position.y+=.12;}
 if(railMotion.snapshot().phase==='travel'&&steamClock>.22){steamClock=0;const p=steam[steamCursor++%steam.length];p.life=1;p.m.position.copyFrom(B.Vector3.TransformCoordinates(new B.Vector3(0,3,2.3),train.getWorldMatrix()));}
}
let started=false,mode='world',time=0,keys={},stick={x:0,y:0},destination=null,task=null,answer=null,selected=0,objects=[],objectsIndex=0,puzzleRoot=null,board=null,savedCamera=null,cameraTransition=null,puzzleBounds=null,puzzlePose=null,moving=false,rideSaved=null,wasNear=null,paused=false,quality='auto',qualityTier='balanced',autoQuality=G.adaptive(),audioTicker=0,stepTimer=0,railTimer=0;
function clearCameraInertia(){for(const key of ['inertialAlphaOffset','inertialBetaOffset','inertialRadiusOffset','inertialPanningX','inertialPanningY'])camera[key]=0;}
function restoreCameraControls(){camera.lowerRadiusLimit=savedCamera?.lowerRadiusLimit??6;camera.upperRadiusLimit=savedCamera?.upperRadiusLimit??24;camera.checkCollisions=savedCamera?.checkCollisions??true;camera.attachControl(canvas,true);}
function applyCamera(pose){camera.target.copyFrom(pose.target);camera.alpha=pose.alpha;camera.beta=pose.beta;camera.radius=pose.radius;clearCameraInertia();}
function transitionCamera(pose,duration=.55){const to={...pose,target:new B.Vector3(pose.target.x,pose.target.y,pose.target.z)};if(prefs().motion){applyCamera(to);cameraTransition=null;if(mode==='world')restoreCameraControls();return;}cameraTransition={from:{target:camera.target.clone(),alpha:camera.alpha,beta:camera.beta,radius:camera.radius},to,elapsed:0,duration};clearCameraInertia();}
function tickCamera(dt){if(!cameraTransition)return;const t=cameraTransition;t.elapsed+=dt;const mix=F.ease(t.elapsed/t.duration);camera.target.copyFrom(B.Vector3.Lerp(t.from.target,t.to.target,mix));camera.alpha=t.from.alpha+F.angleDelta(t.from.alpha,t.to.alpha)*mix;camera.beta=t.from.beta+(t.to.beta-t.from.beta)*mix;camera.radius=t.from.radius+(t.to.radius-t.from.radius)*mix;if(t.elapsed>=t.duration){applyCamera(t.to);cameraTransition=null;if(mode==='world')restoreCameraControls();}}
function contentBounds(){const min=new B.Vector3(Infinity,Infinity,Infinity),max=new B.Vector3(-Infinity,-Infinity,-Infinity);for(const m of puzzleRoot.getChildMeshes()){if(m===board)continue;m.computeWorldMatrix(true);const bb=m.getBoundingInfo().boundingBox;min.minimizeInPlace(bb.minimumWorld);max.maximizeInPlace(bb.maximumWorld);}return{min,max};}
function framePuzzle(){if(mode!=='puzzle'||!puzzleRoot)return;const bounds=contentBounds();if(!puzzleBounds)puzzleBounds=bounds;else{puzzleBounds.min.minimizeInPlace(bounds.min);puzzleBounds.max.maximizeInPlace(bounds.max);}const min=puzzleBounds.min,max=puzzleBounds.max;
// Resize the plinth to the activity instead of fitting an oversized one-size-fits-all platform.
board.position.x=(min.x+max.x)/2-puzzleRoot.position.x;board.position.z=(min.z+max.z)/2-puzzleRoot.position.z;board.scaling.x=(max.x-min.x+1.1)/12;board.scaling.z=(max.z-min.z+1.1)/8;board.computeWorldMatrix(true);const floor=board.getBoundingInfo().boundingBox,fitBounds={min:B.Vector3.Minimize(min,floor.minimumWorld),max:B.Vector3.Maximize(max,floor.maximumWorld)};
const frame=api.exerciseFrame?.()||{x:0,y:0,width:1,height:1};camera.viewport=new B.Viewport(frame.x,frame.y,frame.width,frame.height);const aspect=engine.getRenderWidth()*frame.width/(engine.getRenderHeight()*frame.height),pose=F.fit(fitBounds,aspect,camera.fov);camera.maxZ=Math.max(500,pose.radius*3);if(puzzlePose&&Math.abs(puzzlePose.radius-pose.radius)<.001&&['x','y','z'].every(k=>Math.abs(puzzlePose.target[k]-pose.target[k])<.001))return;puzzlePose=pose;transitionCamera(pose,.55);}
function prefs(){return api.prefs();}
function applyQuality(tier){qualityTier=tier;const width=canvas.clientWidth||engine.getRenderWidth(),height=canvas.clientHeight||engine.getRenderHeight(),p=G.profile(tier,width,height,root.devicePixelRatio||1);engine.setHardwareScalingLevel(p.scaling);shadows.getShadowMap().resize(p.shadow);shadows.blurKernel=tier==='high'?24:12;glow.isEnabled=p.glow;pipeline.fxaaEnabled=p.fxaa;framePuzzle();}
function qualitySet(value){quality=['auto','high','low'].includes(value)?value:'auto';autoQuality.reset();applyQuality(quality==='auto'?'balanced':quality);}
const controls=root.MoonControls.create({canvas,joystick:api.joystick,knob:api.knob,
 enabled:()=>started&&(mode==='world'||mode==='ride')&&!api.blocked()&&!cameraTransition,
 movement(x,y){stick={x,y};},cancelMove(){destination=null;},
 viewport:()=>({width:canvas.clientWidth||engine.getRenderWidth(),height:canvas.clientHeight||engine.getRenderHeight()}),
 orbit(dx,dy){if(mode==='ride'){lookRide(dx,dy);return;}clearCameraInertia();camera.alpha-=dx*Math.PI*1.6;camera.beta=Math.max(camera.lowerBetaLimit,Math.min(camera.upperBetaLimit,camera.beta-dy*Math.PI));},
 zoom(ratio){if(mode==='ride')return;clearCameraInertia();camera.radius=Math.max(camera.lowerRadiusLimit,Math.min(camera.upperRadiusLimit,camera.radius*ratio));},
 tap(x,y){if(mode==='ride')return;const rect=canvas.getBoundingClientRect(),bell=scene.pick(x-rect.left,y-rect.top,m=>m.metadata?.station!==undefined);if(bell?.hit){bell.pickedMesh.metadata.use();return;}const hit=scene.pick(x-rect.left,y-rect.top,m=>m===ground);if(hit?.hit)destination=hit.pickedPoint;}
});
function lookRide(dx,dy){rideCamera.rotation.y+=dx*Math.PI*1.6;rideCamera.rotation.x=Math.max(-.65,Math.min(.65,rideCamera.rotation.x+dy*Math.PI));}
let rideMouse=null;
canvas.addEventListener('contextmenu',e=>{if(mode==='ride')e.preventDefault();});
canvas.addEventListener('pointerdown',e=>{if(mode==='ride'&&e.pointerType!=='touch'&&e.button===2&&!api.blocked()){rideMouse={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);}});
canvas.addEventListener('pointermove',e=>{if(!rideMouse||rideMouse.id!==e.pointerId||mode!=='ride'||api.blocked())return;lookRide((e.clientX-rideMouse.x)/(canvas.clientWidth||1),(e.clientY-rideMouse.y)/(canvas.clientHeight||1));rideMouse.x=e.clientX;rideMouse.y=e.clientY;});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{rideMouse=null;});
function moveTrain(state,rollDistance=0){train.position.set(state.x,0,state.z);train.rotation.y=state.heading;for(const wheel of wheels){wheel.metadata.roll-=rollDistance/.32;wheel.rotationQuaternion=B.Quaternion.RotationAxis(B.Vector3.Right(),wheel.metadata.roll).multiply(B.Quaternion.RotationAxis(B.Vector3.Forward(),Math.PI/2));}train.computeWorldMatrix(true);}
function stationUI(){const state=railMotion.snapshot(),index=nearbyStation();api.station?.(index,state);api.callStation?.(index>=0&&(state.active||index!==state.station),state.active,index);api.ride(index>=0&&index===state.station&&!state.active,false,'idle',(state.station+1)%R.stations.length);}
function finishRide(persist=true){if(mode!=='ride')return;const state=railMotion.finish(),p=R.platform(state.station);moveTrain(state);hero.parent=null;hero.position.set(p.x,.25,p.z);hero.setEnabled(true);ghost.parent=null;ghost.position.set(p.x+.7,1.7,p.z+.4);mode='world';scene.activeCamera=camera;controls.reset();keys={};rideMouse=null;destination=null;camera.target.copyFrom(hero.position.add(new B.Vector3(0,1.3,0)));applyCamera({...rideSaved,target:camera.target.clone()});restoreCameraControls();rideSaved=null;stationUI();if(persist){api.position(hero.position.x,hero.position.z);api.trainStation?.(state.station);}}
function nearbyStation(){return R.stations.findIndex((s,i)=>{const p=R.platform(i);return Math.hypot(hero.position.x-p.x,hero.position.z-p.z)<4;});}
function callTrain(requested){const index=nearbyStation();if(!started||mode!=='world'||api.blocked()||index<0||(requested!==undefined&&requested!==index)||!railMotion.call(index))return false;moveTrain(railMotion.snapshot());stationUI();api.effect('train',{gain:.35});return true;}
function tickCalledTrain(dt){const before=railMotion.snapshot(),state=railMotion.tick(dt);moveTrain(state,Math.max(0,state.travelled-before.travelled));if(!state.active)api.trainStation?.(state.station);}
function boardTrain(target){const state=railMotion.snapshot();if(!started||mode!=='world'||api.blocked()||nearbyStation()!==state.station||!railMotion.begin(target))return false;
 controls.reset();keys={};destination=null;cameraTransition=null;rideSaved={alpha:camera.alpha,beta:camera.beta,radius:camera.radius};camera.detachControl();clearCameraInertia();moveTrain(railMotion.snapshot());
 hero.parent=train;hero.position.set(0,.65,0);hero.rotation.set(0,0,0);hero.setEnabled(false);ghost.parent=train;ghost.position.set(.65,1.4,.65);ghost.rotation.set(0,Math.PI,0);rideCamera.rotation.set(0,0,0);rideCamera.position.set(-4*railMotion.snapshot().direction,1.95,-.35);scene.activeCamera=rideCamera;mode='ride';api.near(null);wasNear=null;api.callStation?.(false);api.station?.(-1,railMotion.snapshot());api.ride(true,true,'boarding',railMotion.snapshot().target);api.effect('train');return true;
}
function tickRide(dt){const before=railMotion.snapshot(),state=railMotion.tick(dt);moveTrain(state,Math.max(0,state.travelled-before.travelled));
 const t=state.phase==='boarding'?F.ease(state.progress):1;rideCamera.position.set(-4*state.direction*(1-t),1.95+.1*t,-.35);hero.computeWorldMatrix(true);ghost.computeWorldMatrix(true);
 railTimer+=dt;if(state.phase==='travel'&&railTimer>.75){railTimer=0;api.effect('train',{gain:.16});}api.ride(true,true,state.phase,state.target);if(!state.active)finishRide();
}
function interactable(m,name,fn){m.isPickable=true;m.metadata={use:fn,name};objects.push({m,name,fn});return m;}
function disposable(){if(puzzleRoot){const children=puzzleRoot.getChildMeshes();for(const m of children){if(m.material?.name.startsWith('tile-')||m.material?.name.startsWith('label-')){m.material.diffuseTexture?.dispose();m.material.dispose();}}puzzleRoot.dispose();puzzleRoot=null;}objects=[];}
function tile(text,x,z,fn,mat=stone,size=1.2){const m=box('puzzle-tile',[x,.3,z],[size,.35,size],mat,puzzleRoot);textTop(text,[x,.49,z],size*.85,puzzleRoot);if(fn)interactable(m,String(text),fn);return m;}
function change(next){if(api.solved())return;answer=next;api.change(next);renderPuzzle();}
function beam(result){for(const segment of result.segments){const p1=segment.from,p2=segment.to,v1=new B.Vector3(p1.x*1.2-1.8,.9,p1.y*1.2-1.8),v2=new B.Vector3(p2.x*1.2-1.8,.9,p2.y*1.2-1.8),dir=v2.subtract(v1).normalize();
 const m=mesh('CreateTube','light-beam',{path:[v1,v2],radius:segment.intensity<1?.027:.035,tessellation:8},[0,0,0],warm,puzzleRoot);m.metadata={segment};
 const midpoint=B.Vector3.Lerp(v1,v2,.62),arrow=cyl('beam-direction',midpoint.asArray(),.2,.14,warm,puzzleRoot,0);arrow.rotationQuaternion=B.Quaternion.RotationAxis(B.Vector3.Cross(B.Vector3.Up(),dir).normalize(),Math.PI/2);
}}
function drawOptic(type,orientation,pos,size=1){const silver=material('mirror-silver','#dbe4ed');silver.specularColor=B.Color3.White();silver.specularPower=96;
 const interfaceMat=material('splitter-interface','#b0d4e0');interfaceMat.alpha=.5;interfaceMat.specularColor=B.Color3.White();const coating=box(type==='splitter'?'splitter-coating':'mirror',pos,[.9*size,.7*size,.025*size],type==='splitter'?interfaceMat:silver,puzzleRoot);coating.rotation.y=orientation===0?Math.PI/4:-Math.PI/4;
 for(const y of [-.37,.37])box('mirror-frame',[0,y*size,0],[.99*size,.065*size,.07*size],gold,coating);
 for(const x of [-.48,.48])box('mirror-frame',[x*size,0,0],[.05*size,.75*size,.07*size],gold,coating);
 if(type==='splitter'){const prism=material('splitter-glass','#8fdbed',.08);prism.alpha=.28;prism.specularColor=B.Color3.White();box('beam-splitting-prism',pos,[.85*size,.72*size,.85*size],prism,puzzleRoot);}
 return coating;
}
function renderPuzzle(){if(!task)return;disposable();puzzleRoot=new B.TransformNode('puzzle',scene);const p=sites[task.area];puzzleRoot.position.set(p.x,.1,p.z-5);board=box('puzzle-plinth',[0,0,0],[12,.25,8],material('puzzle-floor','#52616b'),puzzleRoot);board.isPickable=true;board.metadata={board:true};let q=task;
if(q.type==='groups'){const available=q.total-answer.reduce((s,v)=>s+v,0);for(let i=0;i<q.groups;i++){const x=(i-(q.groups-1)/2)*2.4;cyl('basket',[x,.55,0],.7,1.8,wood,puzzleRoot,2);label(answer[i]+' / '+q.targets[i],[x,1.3,-.8],2,puzzleRoot);for(let n=0;n<answer[i];n++)ell('collected-light',[x+((n%4)-1.5)*.25,.95+Math.floor(n/4)*.15,0],[.16,.16,.16],warm,puzzleRoot);const m=box('basket-click',[x,.6,0],[2,1,1.8],material('invisible','#778899'),puzzleRoot);m.visibility=.001;interactable(m,(api.lang()==='fr'?'Panier ':'Mand ')+(i+1),()=>{if(available>0){const a=[...answer];a[i]++;change(a);}});m.metadata.drop='firefly';tile('−',x,2,()=>{if(answer[i]>(i===0?q.initial:0)){const a=[...answer];a[i]--;change(a);}},roof,.8);}label(String(available)+' '+(api.lang()==='fr'?'lucioles':'lichtjes'),[0,2.2,2.5],5,puzzleRoot);if(available>0){const source=ell('loose-fireflies',[0,.65,2.7],[.55,.55,.55],warm,puzzleRoot);interactable(source,api.lang()==='fr'?'Luciole à déplacer':'Vuurvliegje om te verplaatsen',()=>{});source.metadata.drag='firefly';}}
if(q.type==='fraction'){for(let i=0;i<q.total;i++){const x=(i%6-2.5)*1.3,z=Math.floor(i/6)*1.3-1;const m=cyl('potion-well',[x,.35,z],.35,1,answer[i]===null?wood:answer[i]===0?blue:pink,puzzleRoot);interactable(m,(api.lang()==='fr'?'Mesure ':'Vak ')+(i+1),()=>{const a=[...answer];a[i]=selected;change(a);});m.metadata.drop='drop';}for(let i=0;i<2;i++){const bottle=cyl('bottle',[-3+i*6,1,-2.8],1.5,.6,i===0?blue:pink,puzzleRoot,.35);interactable(bottle,i===0?(api.lang()==='fr'?'Bleu':'Blauw'):(api.lang()==='fr'?'Rouge':'Rood'),()=>{selected=i;api.select(i);});bottle.metadata.drag='drop';bottle.metadata.colour=i;}label(q.num+'/'+q.den+' · '+q.total,[0,2.5,0],4,puzzleRoot);}
if(q.type==='word'){const letters=Array.from(q.word);for(let i=0;i<letters.length;i++){const x=(i-(letters.length-1)/2)*1.1;const used=q.tiles.find(v=>v.id===answer[i]);const slot=tile(used?.letter||'?',x,-.8,()=>{if(answer[i]!==undefined)change(answer.filter((_,j)=>i!==j));},roof,.95);slot.metadata.name=(api.lang()==='fr'?'Retirer la lettre ':'Verwijder letter ') +(i+1);objects.at(-1).name=slot.metadata.name;}q.tiles.forEach((v,i)=>{if(answer.includes(v.id))return;const letter=tile(v.letter,(i-(q.tiles.length-1)/2)*1.1,1.5,()=>{if(answer.length<letters.length)change([...answer,v.id]);},gold,.95);letter.metadata.drag='letter';});}
if(q.type==='sequence'){q.values.forEach((v,i)=>tile(i===q.missing?(answer??'?'):v,(i-(q.n-1)/2)*1.35,-.6,null,i===q.missing?gold:stone));q.choices.forEach((v,i)=>tile(v,(i-1)*2,2,()=>change(v),roof));}
if(q.type==='riddle'||q.type==='deduction'){q.choices.forEach((v,i)=>{const value=q.type==='riddle'?v.value:i,text=q.type==='riddle'?v.label:v;const x=(i-1)*3;const choice=tile(text[0].toUpperCase(),x,0,()=>change(value),answer===value?gold:roof,1.6);choice.metadata.name=text;objects.at(-1).name=text;label(text,[x,1.8,0],2.5,puzzleRoot);if(q.type==='riddle'&&v.value==='moon')ell('moon-object',[x,1,0],[.7,.7,.7],warm,puzzleRoot);if(q.type==='riddle'&&v.value==='book')box('book-object',[x,1,0],[.8,.12,.55],pink,puzzleRoot);if(q.type==='riddle'&&v.value==='clock'){const c=cyl('clock-object',[x,1,0],.15,.8,plaster,puzzleRoot);c.rotation.x=Math.PI/2;}});}
if(q.type==='pattern'){const glyph=['☾','★','❧'];q.sequence.forEach((v,i)=>tile(i===q.missing?(answer===null?'?':glyph[answer]):glyph[v],(i-(q.sequence.length-1)/2)*.78,-.8,null,i===q.missing?gold:roof,.7));[0,1].forEach((v,i)=>tile(glyph[v],(i-.5)*2,2,()=>change(v),gold));}
if(q.type==='mirror'){const E=root.MoonEngine,result=E.trace(q,answer),fr=api.lang()==='fr';
 for(let x=0;x<4;x++)for(let y=0;y<4;y++)box('optics-grid-cell',[x*1.2-1.8,.3,y*1.2-1.8],[1,.35,1],stone,puzzleRoot);
 q.mirrors.forEach((v,i)=>{const state=E.optic(answer[i]),pos=[v.x*1.2-1.8,.9,v.y*1.2-1.8];
 const socket=cyl('reflector-socket',[pos[0],.55,pos[2]],.15,.85,dark,puzzleRoot),m=state?.type?drawOptic(state.type,state.orientation,pos):socket;
 m.metadata={opticIndex:i,orientation:state?.orientation,type:state?.type};
 interactable(socket,(fr?'Emplacement ':'Plaats ')+(i+1)+' · '+(state?.type==='splitter'?(fr?'prisme':'prisma'):state?.type?(fr?'miroir':'spiegel'):(fr?'vide':'leeg')),()=>{
  if(q.optics){const next=E.placeOptic(q,answer,i,selected===2?null:selected===1?'splitter':'mirror');if(next)change(next);else api.opticBlocked?.();}
  else {const next=[...answer];next[i]=1-next[i];change(next);}
 });m.isPickable=true;m.metadata={...socket.metadata,opticIndex:i,orientation:state?.orientation,type:state?.type};socket.metadata.opticIndex=i;
 textTop(i+1,[pos[0]+.43,.5,pos[2]-.43],.25,puzzleRoot);
 });beam(result);ell('light-source',[-3,.9,-.6],[.35,.35,.35],warm,puzzleRoot);
 (q.targets||[q.exit]).forEach((target,i)=>{ell('target-light',[target.x*1.2-1.8,.9,target.y*1.2-1.8],[.5,.8,.5],result.lit.includes(i)?warm:dark,puzzleRoot);textTop(i+1,[target.x*1.2-1.8,.46,target.y*1.2-1.8],.4,puzzleRoot);});
 if(q.optics){const stock=E.remaining(q,answer);box('reflector-tray',[0,.35,4],[4,.2,1.2],wood,puzzleRoot);label(fr?'Réserve limitée':'Beperkte voorraad',[0,1.35,4],3,puzzleRoot);
 let x=-1.5;for(const type of ['mirror','splitter'])for(let n=0;n<stock[type];n++){const item=drawOptic(type,0,[x,.85,4],.55);interactable(item,type==='mirror'?(fr?'Choisir miroir':'Kies spiegel'):(fr?'Choisir prisme':'Kies prisma'),()=>{selected=type==='mirror'?0:1;api.select(selected);});x+=.8;}
 }
}
if(q.type==='time'){const face=cyl('clock-face',[0,.35,0],.15,4,plaster,puzzleRoot);for(let i=1;i<=12;i++){const a=i*Math.PI/6;textTop(i,[Math.sin(a)*1.6,.46,Math.cos(a)*1.6],.35,puzzleRoot);}const ha=answer%720/720*Math.PI*2,ma=answer%60/60*Math.PI*2;for(const [a,len,mat]of [[ha,1,dark],[ma,1.5,gold]]){const h=box('clock-hand',[Math.sin(a)*len/2,.52,Math.cos(a)*len/2],[.1,.08,len],mat,puzzleRoot);h.rotation.y=a;}interactable(face,api.lang()==='fr'?'Minutes':'Minuten',()=>{});face.metadata.clock=true;label(api.time(answer),[0,2.2,2.5],3,puzzleRoot);label((q.kind==='schedule'?'−':'+')+q.duration+' min · '+api.time(q.start),[0,2.5,-2.7],6,puzzleRoot);}
if(q.type==='route'){const {x:px,y:py}=P.routePosition(answer);for(let x=0;x<3;x++)for(let y=0;y<3;y++)tile(x===px&&y===py?'●':x===q.target[0]&&y===q.target[1]?'★':'·',(x-1)*1.8,(y-1)*1.8,null,x===q.target[0]&&y===q.target[1]?gold:stone,1.4);for(const [symbol,direction,x,z]of [['↑','N',5.6,1.8],['↓','S',5.6,-1.8],['←','W',3.8,0],['→','E',7.4,0]])tile(symbol,x,z,()=>change(P.routeStep(q,answer,direction)),roof);tile('↶',3.8,-3.6,()=>change(answer.slice(0,-1)),roof);tile('⌧',7.4,-3.6,()=>change(''),roof);}
objectsIndex=Math.min(objectsIndex,Math.max(0,objects.length-1));api.objects(objects.map(o=>o.name),objectsIndex);framePuzzle();}
function enter(q,a){finishRide();controls.reset();savedCamera={alpha:camera.alpha,beta:camera.beta,radius:camera.radius,lowerRadiusLimit:camera.lowerRadiusLimit,upperRadiusLimit:camera.upperRadiusLimit,checkCollisions:camera.checkCollisions,layerMask:camera.layerMask};task=q;answer=a;selected=0;mode='puzzle';scene.fogDensity=0;destination=null;keys={};stick={x:0,y:0};cameraTransition=null;puzzleBounds=null;puzzlePose=null;camera.detachControl();clearCameraInertia();camera.lowerRadiusLimit=2;camera.upperRadiusLimit=null;camera.checkCollisions=false;camera.layerMask=PUZZLE_LAYER;renderPuzzle();}
function leave(){disposable();task=null;puzzleBounds=null;puzzlePose=null;mode='world';camera.layerMask=savedCamera?.layerMask??0x0fffffff;camera.viewport=new B.Viewport(0,0,1,1);if(savedCamera)transitionCamera({...savedCamera,target:hero.position.add(new B.Vector3(0,1.3,0))},.45);else restoreCameraControls();api.objects([],0);}
function teleport(area){finishRide(false);controls.reset();api.effect('path');const p=sites[area];hero.position.set(p.x,terrainHeight(p.x,p.z-2.5),p.z-2.5);destination=null;if(mode==='world'){if(cameraTransition){applyCamera(cameraTransition.to);cameraTransition=null;restoreCameraControls();}camera.target.copyFrom(hero.position.add(new B.Vector3(0,1.3,0)));}api.position(hero.position.x,hero.position.z);api.trainStation?.(railMotion.snapshot().station);}
function celebration(area){const m=lanterns[area];m.scaling.set(1.8,1.8,1.8);api.effect('solve');setTimeout(()=>api.effect('lantern'),450);setTimeout(()=>api.effect('path'),1200);setTimeout(()=>m.scaling.set(1,1,1),1800);}
function updateWorld(done,names){restoredBridge.forEach(p=>p.setEnabled(done.has('bridge')));celebrationStars.forEach((s,i)=>s.setEnabled(done.size>i));for(const [area,m]of Object.entries(lanterns)){m.material=done.has(area)?warm:blue;const old=siteLabels[area];old.material.diffuseTexture.dispose();old.material.dispose();old.dispose();const p=sites[area];siteLabels[area]=label(names[area],[p.x,4.5,p.z],4);}flowers.forEach((f,i)=>f.scaling.y=done.has('garden')?1.5:1);}
let pointer=null,dragVisual=null;function pickInteractive(){return scene.pick(scene.pointerX,scene.pointerY,m=>m.isPickable&&(mode!=='puzzle'||m.layerMask===PUZZLE_LAYER));}function clockAt(hit){if(!hit?.hit||!puzzleRoot)return;const local=hit.pickedPoint.subtract(puzzleRoot.position),theta=Math.atan2(local.x,local.z),minute=(Math.round((theta+Math.PI*2)%(Math.PI*2)/(Math.PI*2)*60/5)*5)%60;change(Math.floor(answer/60)*60+minute);}
scene.onPointerObservable.add(info=>{if(paused||!started||api.blocked()||(mode==='puzzle'&&api.solved()))return;const e=info.event;if(mode==='ride')return;if(mode==='world'&&e.pointerType==='touch')return;
if(info.type===B.PointerEventTypes.POINTERDOWN&&e.button===0){const hit=pickInteractive();if(mode==='puzzle'){pointer={x:e.clientX,y:e.clientY,meta:hit.pickedMesh?.metadata,point:hit.pickedPoint,moved:false};if(pointer.meta?.drag)api.effect('pickup',{gain:.5});if(pointer.meta?.clock)clockAt(hit);}else{if(hit.hit&&hit.pickedMesh?.metadata?.station!==undefined){hit.pickedMesh.metadata.use();return;}const groundHit=scene.pick(scene.pointerX,scene.pointerY,m=>m===ground);if(groundHit.hit)destination=groundHit.pickedPoint;}}
if(info.type===B.PointerEventTypes.POINTERMOVE&&pointer){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>10)pointer.moved=true;if(pointer.meta?.clock){const hit=scene.pick(scene.pointerX,scene.pointerY,m=>m===board||m===ground);clockAt(hit);}else if(pointer.moved&&pointer.meta?.drag){if(!dragVisual){dragVisual=ell('held-puzzle-object',[0,0,0],[.35,.35,.35],pointer.meta.colour===1?pink:warm);dragVisual.layerMask=PUZZLE_LAYER;}const hit=scene.pick(scene.pointerX,scene.pointerY,m=>m===board||m===ground);if(hit.hit)dragVisual.position.copyFrom(hit.pickedPoint.add(new B.Vector3(0,.65,0)));}}
if(info.type===B.PointerEventTypes.POINTERUP&&pointer){const p=pointer;pointer=null;const hit=pickInteractive(),target=hit.pickedMesh?.metadata;dragVisual?.dispose();dragVisual=null;if(!p.moved){if(!p.meta?.clock)p.meta?.use?.();}else if(p.meta?.drag==='drop'&&target?.drop==='drop'){selected=p.meta.colour;api.select(selected);target.use();}else if(p.meta?.drag==='firefly'&&target?.drop==='firefly'){target.use();}else if(p.meta?.drag==='letter'&&hit.hit){p.meta.use();}}
});canvas.addEventListener('pointercancel',()=>{pointer=null;dragVisual?.dispose();dragVisual=null;});ground.isPickable=true;
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||api.blocked())return;keys[e.key.toLowerCase()]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='r'&&mode==='world')boardTrain(api.trainDestination?.());if(e.key.toLowerCase()==='c'&&mode==='world')callTrain();if(e.key.toLowerCase()==='e'&&mode==='world'&&wasNear)api.interact(wasNear);if(mode==='puzzle'&&['ArrowLeft','ArrowRight','Enter',' '].includes(e.key)){if(e.key==='ArrowLeft')objectsIndex=(objectsIndex-1+objects.length)%objects.length;if(e.key==='ArrowRight')objectsIndex=(objectsIndex+1)%objects.length;if(e.key==='Enter'||e.key===' ')objects[objectsIndex]?.fn();api.objects(objects.map(o=>o.name),objectsIndex);}});window.addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);window.addEventListener('blur',()=>{keys={};stick={x:0,y:0};rideMouse=null;});window.addEventListener('resize',()=>{engine.resize();applyQuality(qualityTier);});
engine.runRenderLoop(()=>{const frameTime=engine.getDeltaTime()/1000,dt=Math.min(frameTime,.04);if(document.hidden)return;paused=api.blocked();if(paused){controls.reset();rideMouse=null;bolt.setEnabled(false);}if(!paused){time+=dt;audioTicker+=dt;if(started&&audioTicker>.2){audioTicker=0;api.audioPosition?.(hero.getAbsolutePosition().x,hero.getAbsolutePosition().z);}const reduced=prefs().motion;const goal=api.goal(),target=sites[goal];beacon.setEnabled(!!target&&mode==='world');if(target){beacon.position.set(target.x,5.3+(reduced?0:Math.sin(time*2)*.2),target.z);beacon.rotation.z=reduced?0:time*.25;}
if(!reduced){fireflies.forEach((m,i)=>{m.position.y=1.6+Math.sin(time+i)*.6;});if(mode!=='ride')ghost.position.y=2+Math.sin(time*2)*.12;waterRipples.forEach((r,i)=>{const s=.8+((time*.2+i*.13)%1);r.scaling.x=r.scaling.z=s;});moonMachine.rotation.z=time*.08;}
if(mode==='world'){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+stick.x,z=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+stick.y;const length=Math.hypot(x,z);let speed=Math.min(1,length);moving=started&&length>.001;let dir=new B.Vector3();if(moving){const forward=new B.Vector3(-Math.cos(camera.alpha),0,-Math.sin(camera.alpha)),right=new B.Vector3(forward.z,0,-forward.x);dir=right.scale(x).add(forward.scale(-z)).normalize();destination=null;}else if(started&&destination){dir=destination.subtract(hero.position);dir.y=0;if(dir.length()<.3)destination=null;else{dir.normalize();moving=true;speed=1;}}if(moving){const next=hero.position.add(dir.scale(dt*5*speed));if(L.validPosition(next)){const obstacle=obstacles.some(o=>Math.abs(next.x-o.x)<o.w/2&&Math.abs(next.z-o.z)<o.d/2)||(()=>{const local=B.Vector3.TransformCoordinates(next,B.Matrix.Invert(train.getWorldMatrix()));return Math.abs(local.x)<1.4&&Math.abs(local.z)<2.2;})();next.y=walkHeight(next.x,next.z);if(!obstacle)hero.position.copyFrom(next);}hero.rotation.y=Math.atan2(-dir.x,-dir.z);if(!reduced)limbs.forEach((m,i)=>m.rotation.x=Math.sin(time*8+(i%2)*Math.PI)*.4*speed);}else limbs.forEach(m=>m.rotation.x*=.85);
if(moving){stepTimer+=dt;if(stepTimer>.4){stepTimer=0;const surface=Math.abs(hero.position.x+9)<3?'wood':Math.abs(hero.position.x)>10&&hero.position.z<12?'leaves':'stone';api.effect('footstep-'+surface,{gain:.35});}}else stepTimer=0;
if(started){const follow=hero.position.add(new B.Vector3(0,1.3,0));if(cameraTransition)cameraTransition.to.target.copyFrom(follow);else camera.target.copyFrom(B.Vector3.Lerp(camera.target,follow,reduced?1:F.followWeight(dt)));}else{camera.alpha=-Math.PI/2+.2;camera.beta=.92;camera.radius=28;camera.target.set(0,2,4);}
ghost.position.x+=(hero.position.x+1.2-ghost.position.x)*Math.min(1,dt*4);ghost.position.z+=(hero.position.z+.3-ghost.position.z)*Math.min(1,dt*4);ghost.rotation.y=hero.rotation.y;
let near=null,min=5;for(const [area,p]of Object.entries(sites)){const d=Math.hypot(hero.position.x-p.x,hero.position.z-p.z);if(d<min){near=area;min=d;}}if(near!==wasNear){wasNear=near;api.near(near);}if(railMotion.snapshot().summoned)tickCalledTrain(dt);stationUI();if(moving&&Math.floor(time*10)%30===0)api.position(hero.position.x,hero.position.z);
}else if(mode==='ride')tickRide(dt);
}if(!paused){weatherTick(dt);tickCamera(dt);}scene.render();if(quality==='auto'&&!paused&&started){const tier=autoQuality.sample(frameTime);if(tier)applyQuality(tier);}});
qualitySet('auto');return{engine,scene,hero,camera,sites,stations:R.stations,railState:()=>railMotion.snapshot(),start(pos,station){finishRide(false);if(railMotion.snapshot().active)railMotion.finish();railMotion.park(Number.isInteger(station)?station:0);moveTrain(railMotion.snapshot());controls.reset();started=true;if(pos&&L.validPosition(pos))hero.position.set(pos.x,walkHeight(pos.x,pos.z),pos.z);if(mode==='world'){camera.radius=14;camera.beta=1.06;camera.target.copyFrom(hero.position.add(new B.Vector3(0,1.3,0)));clearCameraInertia();}},enter,leave,teleport,refit:framePuzzle,change(a){answer=a;renderPuzzle();},select(i){selected=i;},objectsMove(d){if(!objects.length)return;objectsIndex=(objectsIndex+d+objects.length)%objects.length;api.objects(objects.map(o=>o.name),objectsIndex);},objectsUse(){objects[objectsIndex]?.fn();},celebration,updateWorld,setStick(x,y){stick={x,y};},quality:qualitySet,avatar(coat,skin){coatMat.diffuseColor=B.Color3.FromHexString({teal:'#4caaaa',plum:'#ab79a3',amber:'#d5a254'}[coat]||'#4caaaa');skinMat.diffuseColor=B.Color3.FromHexString({light:'#d7aa86',medium:'#ac785a',dark:'#714a39'}[skin]||'#d7aa86');},ride:boardTrain,callTrain,resetInput(){keys={};rideMouse=null;controls.reset();},stop(){controls.dispose();engine.dispose();}};
}
root.MoonWorld={create};})(window);
