/* Original procedural 3D artwork and direct world interactions. Babylon.js Apache-2.0. */
(function(root){'use strict';
function create(canvas,api){const B=root.BABYLON;if(!B||!B.Engine.isSupported())throw Error('WebGL');const engine=new B.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,powerPreference:'high-performance'}),scene=new B.Scene(engine);scene.clearColor=new B.Color4(.065,.105,.18,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.008;scene.fogColor=new B.Color3(.14,.22,.31);scene.collisionsEnabled=true;
const camera=new B.ArcRotateCamera('camera',-Math.PI/2,1.06,18,new B.Vector3(0,2,0),scene);camera.lowerBetaLimit=.45;camera.upperBetaLimit=1.25;camera.lowerRadiusLimit=9;camera.upperRadiusLimit=24;camera.wheelPrecision=25;camera.attachControl(canvas,true);camera.panningSensibility=0;camera.inputs.removeByType('ArcRotateCameraKeyboardMoveInput');camera.inputs.attached.pointers.buttons=[2];camera.minZ=.2;camera.maxZ=180;
const hemi=new B.HemisphericLight('moonwash',new B.Vector3(0,1,0),scene);hemi.intensity=.75;hemi.diffuse=new B.Color3(.65,.79,1);hemi.groundColor=new B.Color3(.32,.22,.28);const moonLight=new B.DirectionalLight('moonlight',new B.Vector3(-.4,-1,.3),scene);moonLight.position=new B.Vector3(25,40,-30);moonLight.intensity=1.1;moonLight.diffuse=new B.Color3(.91,.85,1);
const shadows=new B.ShadowGenerator(1024,moonLight);shadows.useBlurExponentialShadowMap=true;shadows.blurKernel=12;const glow=new B.GlowLayer('lantern-glow',scene,{mainTextureRatio:.5});glow.intensity=.45;
const mats={};function material(name,hex,em=0){if(mats[name])return mats[name];const m=new B.StandardMaterial(name,scene);m.diffuseColor=B.Color3.FromHexString(hex);m.specularColor=new B.Color3(.12,.12,.12);if(em)m.emissiveColor=m.diffuseColor.scale(em);mats[name]=m;return m;}
const grass=material('moss','#3d6462'),stone=material('stone','#738793'),path=material('warm-path','#a3947f'),wood=material('wood','#715640'),roof=material('roof','#654b70'),plaster=material('plaster','#d5bd99'),gold=material('gold','#edbc67'),dark=material('dark','#273345'),warm=material('warm-light','#ffcc72',1.4),blue=material('moon-drop','#86dbe3',.7),pink=material('red-drop','#dd8ca3',.5),ghostMat=material('Lumi','#c4e7f5',.5),coatMat=material('coat','#4caaaa'),skinMat=material('skin','#d7aa86'),hair=material('hair','#523f48');
let allStatic=[],obstacles=[];function mesh(kind,name,opt,pos,mat,parent=null){let m=B.MeshBuilder[kind](name,opt,scene);m.position=new B.Vector3(...pos);m.material=mat;if(parent)m.parent=parent;m.isPickable=false;if(kind!=='CreatePlane'){m.receiveShadows=true;allStatic.push(m);}return m;}
const box=(n,p,s,m,parent)=>mesh('CreateBox',n,{width:s[0],height:s[1],depth:s[2]},p,m,parent),ball=(n,p,s,m,parent)=>mesh('CreateSphere',n,{diameter:1,segments:12},p,m,parent);function ell(n,p,s,m,parent){const o=ball(n,p,s,m,parent);o.scaling=new B.Vector3(...s);return o;}function cyl(n,p,h,d,m,parent,top=d){return mesh('CreateCylinder',n,{height:h,diameter:d,diameterTop:top,tessellation:16},p,m,parent);}
function label(text,pos,width=3,parent=null){const tx=new B.DynamicTexture('letter-'+text,{width:512,height:128},scene,false);tx.hasAlpha=true;tx.drawText(text,null,88,'bold 60px sans-serif','#fff3d4','#172b3bea',true);const mat=new B.StandardMaterial('label-'+text,scene);mat.diffuseTexture=tx;mat.emissiveColor=B.Color3.White();mat.disableLighting=true;mat.backFaceCulling=false;const m=mesh('CreatePlane','label',{width,height:width/4},pos,mat,parent);return m;}
function textTop(text,pos,size=1,parent){const tx=new B.DynamicTexture('tile-'+text,{width:256,height:256},scene,false);tx.drawText(String(text),null,165,'bold 120px sans-serif','#fff3d4','#31485d',true);const mat=new B.StandardMaterial('tile-text',scene);mat.diffuseTexture=tx;mat.emissiveColor=new B.Color3(.4,.4,.4);const m=mesh('CreatePlane','tile-label',{size},pos,mat,parent);m.rotation.x=Math.PI/2;return m;}
const ground=mesh('CreateGround','earth',{width:140,height:140,subdivisions:1},[0,0,10],grass);const gt=new B.DynamicTexture('moss-texture',{width:512,height:512},scene,false),ctx=gt.getContext();ctx.fillStyle='#416763';ctx.fillRect(0,0,512,512);let rng=root.MoonCampaign.rngFor('world');for(let i=0;i<3500;i++){ctx.fillStyle=['#385854','#4b7065','#5f7664','#876d57'][Math.floor(rng()*4)];ctx.fillRect(rng()*512,rng()*512,2,2);}gt.update();grass.diffuseTexture=gt;gt.uScale=20;gt.vScale=20;
const waterMat=material('stream','#4d9aa6',.08);waterMat.alpha=.78;waterMat.specularColor=new B.Color3(.6,.8,1);const stream=box('stream',[-9,.025,0],[5,.08,85],waterMat);const waterRipples=[];for(let i=0;i<22;i++){const r=mesh('CreateTorus','ripple',{diameter:1.5,thickness:.018,tessellation:24},[-9+(rng()-.5)*3,.09,-35+i*3.3],blue);waterRipples.push(r);}
const sites={bridge:{x:-21,z:-13},garden:{x:19,z:-13},library:{x:-22,z:20},clock:{x:20,z:21},lights:{x:0,z:43}};
function road(x,z){const distance=Math.hypot(x,z),count=Math.ceil(distance/2.5);for(let i=0;i<=count;i++){let t=i/count;const m=cyl('path',[x*t,.03,z*t],.06,3.9,path);m.rotation.y=rng();}}
Object.values(sites).forEach(p=>road(p.x,p.z));cyl('village-square',[0,.04,0],.08,13,path);
function pumpkin(x,z,scale=1,parent=null){const y=scale*.42;const p=new B.TransformNode('pumpkin',scene);p.position=new B.Vector3(x,0,z);if(parent)p.parent=parent;ell('pumpkin',[0,y,0],[scale,scale*.8,scale],material('pumpkin','#d88739'),p);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ell('rib',[Math.sin(a)*scale*.19,y,Math.cos(a)*scale*.19],[scale*.5,scale*.76,scale*.5],material('pumpkin-gold','#e5a244'),p);}cyl('stem',[0,scale*.9,0],scale*.22,scale*.14,wood,p);ell('eye',[-scale*.17,y+scale*.1,-scale*.45],[scale*.1,scale*.12,scale*.05],warm,p);ell('eye',[scale*.17,y+scale*.1,-scale*.45],[scale*.1,scale*.12,scale*.05],warm,p);box('smile',[0,y-scale*.13,-scale*.46],[scale*.22,scale*.05,.04],dark,p);return p;}
function tree(x,z,size=1,colour=0){obstacles.push({x,z,w:.9*size,d:.9*size});const trunk=cyl('tree',[x,2*size,z],4*size,.65*size,wood,null,.42*size);trunk.rotation.z=(rng()-.5)*.1;const colors=['#b8794e','#d39d56','#b7736d','#617f75'];for(let i=0;i<3;i++)ell('autumn-crown',[x+(i-1)*1.2*size,(4.3+i*.65)*size,z+(i%2)*.5],[3.7*size,2.6*size,3.5*size],material('foliage'+colour,colors[colour]));}
for(let i=0;i<65;i++){const x=(rng()-.5)*105,z=(rng()-.25)*95;if(Math.abs(x)<7||Object.values(sites).some(p=>Math.hypot(x-p.x,z-p.z)<9))continue;tree(x,z,.65+rng()*.7,Math.floor(rng()*4));}
function cottage(x,z,s=1){obstacles.push({x,z,w:5*s+.5,d:4*s+.5});box('cottage',[x,1.8*s,z],[5*s,3.6*s,4*s],plaster);const r=cyl('roof',[x,4.25*s,z],2.3*s,7.5*s,roof,null,0);r.rotation.y=Math.PI/4;r.scaling.z=.9;box('door',[x,1.1*s,z-2.03*s],[1.1*s,2.2*s,.12],wood);for(const dx of [-1.55,1.55]){box('window',[x+dx*s,2*s,z-2.08*s],[.95*s,1.1*s,.1],warm);box('window-bar',[x+dx*s,2*s,z-2.15*s],[.07,1.2*s,.1],wood);}box('chimney',[x+1.5*s,4.7*s,z+.4*s],[.65*s,2*s,.8*s],stone);}
cottage(-5,-12,.8);cottage(5,-10,.9);cottage(-4,11,.8);cottage(7,10,.7);cottage(-25,25,1.2);
// Garden glasshouse, beds and luminous plants.
obstacles.push({x:22,z:-19,w:8.5,d:6.5},{x:21,z:27,w:5,d:5},{x:0,z:49,w:14,d:6.5});
const glass=material('glass','#97d9cb',.12);glass.alpha=.4;box('greenhouse',[22,2,-19],[8,4,6],glass);for(let x=18;x<=26;x+=2)box('frame',[x,2,-22],[.12,4,.15],gold);for(let z=-22;z<=-16;z+=2)box('frame',[18,2,z],[.12,4,.15],gold);const flowers=[];for(let i=0;i<18;i++){const x=13+(i%6)*2,z=-18+Math.floor(i/6)*2;box('garden-bed',[x,.2,z],[1.8,.3,1.6],wood);cyl('stem',[x,.9,z],1.3,.08,grass);const flower=ell('moonflower',[x,1.6,z],[.8,.4,.8],material('flower'+i%3,['#bc8ecc','#e6b28c','#9bd2cb'][i%3],.25));flowers.push(flower);}
// Tall moon clock and railway.
cyl('tower',[21,5.5,27],11,4.5,stone);cyl('tower-roof',[21,12,27],3,6,roof,null,0);const clockFace=cyl('tower-clock',[21,8,24.65],.2,3,plaster);clockFace.rotation.x=Math.PI/2;const towerHands=[box('hour-hand',[21,8.3,24.45],[.12,.9,.08],dark),box('minute-hand',[21.6,8,24.43],[1.3,.09,.08],dark)];for(let i=0;i<12;i++){const a=i*Math.PI/6;ell('hour-marker',[21+Math.sin(a)*1.22,8+Math.cos(a)*1.22,24.42],[.1,.1,.06],gold);}
for(let i=0;i<20;i++){const z=-3+i*1.8;box('rail-tie',[12,.09,z],[3,.12,.4],wood);}box('rail',[11,.17,14],[.12,.12,36],stone);box('rail',[13,.17,14],[.12,.12,36],stone);const train=new B.TransformNode('moon-express',scene);train.position=new B.Vector3(12,0,12);box('carriage',[0,1.2,0],[2.5,1.6,4],material('train','#607999'),train);box('carriage-roof',[0,2.3,0],[2.9,.25,4.5],roof,train);for(const x of [-1.3,1.3])for(const z of [-1.2,1.2]){const wheel=cyl('wheel',[x,.4,z],.3,.9,dark,train);wheel.rotation.z=Math.PI/2;}pumpkin(0,-1.8,.8,train);
// Friendly castle and observatory.
box('castle',[0,4,49],[11,8,6],stone);for(const x of [-6,6]){cyl('castle-tower',[x,5,49],10,3,stone);cyl('spire',[x,11,49],4,4,roof,null,0);}box('castle-door',[0,1.9,45.9],[2.5,3.8,.15],wood);for(const x of [-3.5,3.5])for(const y of [3,6])box('castle-window',[x,y,45.9],[1,1.4,.15],warm);const moonMachine=mesh('CreateTorus','moon-machine',{diameter:4,thickness:.16,tessellation:40},[0,9,48],gold);moonMachine.rotation.x=Math.PI/2;
const moon=ell('moon',[18,39,66],[9,9,1],material('moon','#f1e6ba',1));const stars=[];for(let i=0;i<100;i++){const a=rng()*Math.PI*2,dist=65+rng()*20;stars.push(ell('star',[Math.sin(a)*dist,15+rng()*42,Math.cos(a)*dist],[.09,.09,.09],material('star','#dde6f7',1)));}
const lanterns={},siteLabels={};for(const [area,p]of Object.entries(sites)){cyl('lantern-post',[p.x,1.7,p.z],3.4,.18,wood);box('lantern-frame',[p.x,3.2,p.z],[.8,1,.8],gold);const light=ell('lantern-light',[p.x,3.2,p.z],[.5,.65,.5],warm);lanterns[area]=light;siteLabels[area]=label(area,[p.x,4.5,p.z],4);pumpkin(p.x-1.4,p.z,1);pumpkin(p.x+1.3,p.z+.8,.7);}
for(let i=0;i<20;i++){const a=i*Math.PI*2/20;pumpkin(Math.sin(a)*6,Math.cos(a)*6,.45+rng()*.4);}
for(let i=0;i<22;i++){const x=(rng()-.5)*65,z=rng()*55-20;if(Object.values(sites).some(p=>Math.hypot(x-p.x,z-p.z)<6))continue;cyl('mushroom',[x,.4,z],.8,.2,plaster);ell('mushroom-cap',[x,.85,z],[.9,.35,.9],material('mushroom','#9a6680'));}
// Hero: articulated limbs, lantern, face and scarf.
const hero=new B.TransformNode('explorer',scene);hero.position=new B.Vector3(0,0,-3);const body=cyl('coat',[0,1.2,0],1.1,.8,coatMat,hero,.6);ell('head',[0,2.08,0],[.7,.78,.65],skinMat,hero);ell('hair',[0,2.38,.035],[.76,.38,.69],hair,hero);ell('eye',[-.13,2.1,-.3],[.06,.09,.04],dark,hero);ell('eye',[.13,2.1,-.3],[.06,.09,.04],dark,hero);box('smile',[0,1.93,-.32],[.13,.025,.02],dark,hero);const hat=cyl('hat',[0,2.52,0],.4,.8,coatMat,hero,.15);cyl('hat-brim',[0,2.36,0],.08,1.05,coatMat,hero);box('scarf',[0,1.76,-.02],[.75,.15,.65],gold,hero);box('scarf-end',[.2,1.5,-.4],[.18,.55,.08],gold,hero);
const limbs=[];for(const x of [-.25,.25]){const leg=new B.TransformNode('leg',scene);leg.parent=hero;leg.position.set(x,.8,0);cyl('leg',[0,-.28,0],.6,.24,dark,leg);box('boot',[0,-.65,-.09],[.29,.25,.44],wood,leg);limbs.push(leg);}for(const x of [-.47,.47]){const arm=new B.TransformNode('arm',scene);arm.parent=hero;arm.position.set(x,1.6,0);cyl('sleeve',[0,-.25,0],.6,.23,coatMat,arm);ell('hand',[0,-.57,0],[.22,.24,.23],skinMat,arm);limbs.push(arm);}box('held-lantern',[.53,.8,-.1],[.3,.4,.3],warm,hero);const heroLight=new B.PointLight('hero-lantern',new B.Vector3(.5,1,-.3),scene);heroLight.parent=hero;heroLight.diffuse=new B.Color3(1,.74,.37);heroLight.intensity=.5;heroLight.range=6;
const ghost=new B.TransformNode('Lumi',scene);ell('ghost-body',[0,0,0],[.85,1.15,.7],ghostMat,ghost);ell('ghost-eye',[-.15,.13,-.33],[.07,.12,.04],dark,ghost);ell('ghost-eye',[.15,.13,-.33],[.07,.12,.04],dark,ghost);ell('ghost-cheek',[-.23,-.07,-.31],[.14,.07,.04],pink,ghost);ell('ghost-cheek',[.23,-.07,-.31],[.14,.07,.04],pink,ghost);cyl('ghost-hat',[0,.75,0],.65,.65,roof,ghost,0);cyl('ghost-brim',[0,.45,0],.06,.95,roof,ghost);
const fireflies=[];for(let i=0;i<35;i++)fireflies.push(ell('firefly',[(rng()-.5)*55,1+rng()*3,rng()*60-15],[.09,.09,.09],warm));
allStatic.forEach(m=>{if(!m.parent&&m!==moonMachine&&!flowers.includes(m)&&!fireflies.includes(m)&&!waterRipples.includes(m)&&!Object.values(lanterns).includes(m))m.freezeWorldMatrix();});[body,...hero.getChildMeshes()].forEach(m=>shadows.addShadowCaster(m));
const beacon=mesh('CreateTorus','quest-beacon',{diameter:1.8,thickness:.09,tessellation:32},[0,5,0],warm);beacon.rotation.x=Math.PI/2;allStatic.filter(m=>m.name==='cottage'||m.name==='roof'||m.name==='autumn-crown'||m.name==='castle').forEach(m=>shadows.addShadowCaster(m));
let started=false,mode='world',time=0,keys={},stick={x:0,y:0},destination=null,task=null,answer=null,selected=0,objects=[],objectsIndex=0,puzzleRoot=null,board=null,savedCamera=null,moving=false,rideTime=0,rideOrigin=null,wasNear=null,paused=false,quality='auto',slow=0;
function prefs(){return api.prefs();}function qualitySet(value){quality=value;const low=value==='low'||value==='auto'&&(matchMedia('(pointer:coarse)').matches||devicePixelRatio>2);engine.setHardwareScalingLevel(low?Math.max(1.3,devicePixelRatio):Math.max(.75,devicePixelRatio/1.5));shadows.getShadowMap().resize(low?512:1024);glow.isEnabled=!low;}
function interactable(m,name,fn){m.isPickable=true;m.metadata={use:fn,name};objects.push({m,name,fn});return m;}
function disposable(){if(puzzleRoot){const children=puzzleRoot.getChildMeshes();for(const m of children){if(m.material?.name.startsWith('tile-')||m.material?.name.startsWith('label-')){m.material.diffuseTexture?.dispose();m.material.dispose();}}puzzleRoot.dispose();puzzleRoot=null;}objects=[];}
function tile(text,x,z,fn,mat=stone,size=1.2){const m=box('puzzle-tile',[x,.3,z],[size,.35,size],mat,puzzleRoot);textTop(text,[x,.49,z],size*.85,puzzleRoot);if(fn)interactable(m,String(text),fn);return m;}
function change(next){if(api.solved())return;answer=next;api.change(next);renderPuzzle();}
function beam(points){for(let i=1;i<points.length;i++){const v1=new B.Vector3(points[i-1].x*1.2-1.8,.9,points[i-1].y*1.2-1.8),v2=new B.Vector3(points[i].x*1.2-1.8,.9,points[i].y*1.2-1.8),m=mesh('CreateTube','light-beam',{path:[v1,v2],radius:.035,tessellation:6},[0,0,0],warm,puzzleRoot);}}
function renderPuzzle(){if(!task)return;disposable();puzzleRoot=new B.TransformNode('puzzle',scene);const p=sites[task.area];puzzleRoot.position.set(p.x,.1,p.z-5);board=box('puzzle-plinth',[0,0,0],[12,.25,8],material('puzzle-floor','#52616b'),puzzleRoot);board.isPickable=true;board.metadata={board:true};let q=task;
if(q.type==='groups'){const available=q.total-answer.reduce((s,v)=>s+v,0);for(let i=0;i<q.groups;i++){const x=(i-(q.groups-1)/2)*2.4;cyl('basket',[x,.55,0],.7,1.8,wood,puzzleRoot,2);label(answer[i]+' / '+q.targets[i],[x,1.3,-.8],2,puzzleRoot);for(let n=0;n<answer[i];n++)ell('collected-light',[x+((n%4)-1.5)*.25,.95+Math.floor(n/4)*.15,0],[.16,.16,.16],warm,puzzleRoot);const m=box('basket-click',[x,.6,0],[2,1,1.8],material('invisible','#778899'),puzzleRoot);m.visibility=.001;interactable(m,(api.lang()==='fr'?'Panier ':'Mand ')+(i+1),()=>{if(available>0){const a=[...answer];a[i]++;change(a);}});m.metadata.drop='firefly';tile('−',x,2,()=>{if(answer[i]>(i===0?q.initial:0)){const a=[...answer];a[i]--;change(a);}},roof,.8);}label(String(available)+' '+(api.lang()==='fr'?'lucioles':'lichtjes'),[0,2.2,2.5],5,puzzleRoot);if(available>0){const source=ell('loose-fireflies',[0,.65,2.7],[.55,.55,.55],warm,puzzleRoot);interactable(source,api.lang()==='fr'?'Luciole à déplacer':'Vuurvliegje om te verplaatsen',()=>{});source.metadata.drag='firefly';}}
if(q.type==='fraction'){for(let i=0;i<q.total;i++){const x=(i%6-2.5)*1.3,z=Math.floor(i/6)*1.3-1;const m=cyl('potion-well',[x,.35,z],.35,1,answer[i]===null?wood:answer[i]===0?blue:pink,puzzleRoot);interactable(m,(api.lang()==='fr'?'Mesure ':'Vak ')+(i+1),()=>{const a=[...answer];a[i]=selected;change(a);});m.metadata.drop='drop';}for(let i=0;i<2;i++){const bottle=cyl('bottle',[-3+i*6,1,-2.8],1.5,.6,i===0?blue:pink,puzzleRoot,.35);interactable(bottle,i===0?(api.lang()==='fr'?'Bleu':'Blauw'):(api.lang()==='fr'?'Rouge':'Rood'),()=>{selected=i;api.select(i);});bottle.metadata.drag='drop';bottle.metadata.colour=i;}label(q.num+'/'+q.den+' · '+q.total,[0,2.5,0],4,puzzleRoot);}
if(q.type==='word'){const letters=Array.from(q.word);for(let i=0;i<letters.length;i++){const x=(i-(letters.length-1)/2)*1.1;const used=q.tiles.find(v=>v.id===answer[i]);tile(used?.letter||'?',x,-.8,()=>{if(answer[i]!==undefined)change(answer.filter((_,j)=>i!==j));},roof,.95);}q.tiles.forEach((v,i)=>{if(answer.includes(v.id))return;const letter=tile(v.letter,(i-(q.tiles.length-1)/2)*1.1,1.5,()=>{if(answer.length<letters.length)change([...answer,v.id]);},gold,.95);letter.metadata.drag='letter';});}
if(q.type==='sequence'){q.values.forEach((v,i)=>tile(i===q.missing?(answer??'?'):v,(i-(q.n-1)/2)*1.35,-.6,null,i===q.missing?gold:stone));q.choices.forEach((v,i)=>tile(v,(i-1)*2,2,()=>change(v),roof));}
if(q.type==='riddle'||q.type==='deduction'){q.choices.forEach((v,i)=>{const value=q.type==='riddle'?v.value:i,text=q.type==='riddle'?v.label:v;const x=(i-1)*3;tile(text[0].toUpperCase(),x,0,()=>change(value),answer===value?gold:roof,1.6);label(text,[x,1.8,0],2.5,puzzleRoot);if(q.type==='riddle'&&v.value==='moon')ell('moon-object',[x,1,0],[.7,.7,.7],warm,puzzleRoot);if(q.type==='riddle'&&v.value==='book')box('book-object',[x,1,0],[.8,.12,.55],pink,puzzleRoot);if(q.type==='riddle'&&v.value==='clock'){const c=cyl('clock-object',[x,1,0],.15,.8,plaster,puzzleRoot);c.rotation.x=Math.PI/2;}});}
if(q.type==='pattern'){const glyph=['☾','★','❧'];q.sequence.forEach((v,i)=>tile(i===q.missing?(answer===null?'?':glyph[answer]):glyph[v],(i-(q.sequence.length-1)/2)*.78,-.8,null,i===q.missing?gold:roof,.7));[0,1].forEach((v,i)=>tile(glyph[v],(i-.5)*2,2,()=>change(v),gold));}
if(q.type==='mirror'){for(let x=0;x<4;x++)for(let y=0;y<4;y++)tile('·',x*1.2-1.8,y*1.2-1.8,null,stone,1);q.mirrors.forEach((v,i)=>{const m=box('mirror',[v.x*1.2-1.8,.9,v.y*1.2-1.8],[.85,.7,.1],blue,puzzleRoot);m.rotation.y=answer[i]===0?-Math.PI/4:Math.PI/4;interactable(m,(api.lang()==='fr'?'Miroir ':'Spiegel ')+(i+1),()=>{const a=[...answer];a[i]=1-a[i];change(a);});});beam(root.MoonEngine.trace(q,answer).points);ell('target-light',[q.exit.x*1.2-1.8,.9,q.exit.y*1.2-1.8],[.5,.8,.5],gold,puzzleRoot);}
if(q.type==='time'){const face=cyl('clock-face',[0,.35,0],.15,4,plaster,puzzleRoot);for(let i=1;i<=12;i++){const a=i*Math.PI/6;textTop(i,[Math.sin(a)*1.6,.46,-Math.cos(a)*1.6],.35,puzzleRoot);}const ha=answer%720/720*Math.PI*2,ma=answer%60/60*Math.PI*2;for(const [a,len,mat]of [[ha,1,dark],[ma,1.5,gold]]){const h=box('clock-hand',[Math.sin(a)*len/2,.52,-Math.cos(a)*len/2],[.1,.08,len],mat,puzzleRoot);h.rotation.y=-a;}interactable(face,api.lang()==='fr'?'Minutes':'Minuten',()=>{});face.metadata.clock=true;label(api.time(answer),[0,2.2,2.5],3,puzzleRoot);label((q.kind==='schedule'?'−':'+')+q.duration+' min · '+api.time(q.start),[0,2.5,-2.7],6,puzzleRoot);}
if(q.type==='route'){let px=0,py=0;for(const c of answer){if(c==='E')px++;else py++;}for(let x=0;x<3;x++)for(let y=0;y<3;y++)tile(x===px&&y===py?'●':x===q.target[0]&&y===q.target[1]?'★':'·',(x-1)*1.8,(1-y)*1.8,null,x===q.target[0]&&y===q.target[1]?gold:stone,1.4);tile('→',3.8,0,()=>{if(answer.length<q.moves)change(answer+'E');},roof);tile('↑',3.8,-2,()=>{if(answer.length<q.moves)change(answer+'N');},roof);tile('↶',3.8,2,()=>change(answer.slice(0,-1)),roof);}
objectsIndex=Math.min(objectsIndex,Math.max(0,objects.length-1));api.objects(objects.map(o=>o.name),objectsIndex);}
function enter(q,a){task=q;answer=a;selected=0;mode='puzzle';destination=null;savedCamera={alpha:camera.alpha,beta:camera.beta,radius:camera.radius};camera.detachControl();camera.alpha=-Math.PI/2;camera.beta=.52;camera.radius=17;const p=sites[q.area];camera.setTarget(new B.Vector3(p.x,.3,p.z-5));renderPuzzle();}
function leave(){disposable();task=null;mode='world';if(savedCamera){camera.alpha=savedCamera.alpha;camera.beta=savedCamera.beta;camera.radius=savedCamera.radius;}camera.attachControl(canvas,true);api.objects([],0);}
function teleport(area){const p=sites[area];hero.position.set(p.x,0,p.z-2.5);destination=null;api.position(hero.position.x,hero.position.z);}
function celebration(area){const m=lanterns[area];m.scaling.set(1.8,1.8,1.8);api.effect('solve');setTimeout(()=>m.scaling.set(1,1,1),1800);}
function updateWorld(done,names){for(const [area,m]of Object.entries(lanterns)){m.material=done.has(area)?warm:blue;const old=siteLabels[area];old.material.diffuseTexture.dispose();old.material.dispose();old.dispose();const p=sites[area];siteLabels[area]=label(names[area],[p.x,4.5,p.z],4);}flowers.forEach((f,i)=>f.scaling.y=done.has('garden')?1.5:1);}
let pointer=null,dragVisual=null;function pickInteractive(){return scene.pick(scene.pointerX,scene.pointerY,m=>m.isPickable);}function clockAt(hit){if(!hit?.hit||!puzzleRoot)return;const local=hit.pickedPoint.subtract(puzzleRoot.position),theta=Math.atan2(local.x,-local.z),minute=(Math.round((theta+Math.PI*2)%(Math.PI*2)/(Math.PI*2)*60/5)*5)%60;change(Math.floor(answer/60)*60+minute);}
scene.onPointerObservable.add(info=>{if(paused||!started||api.blocked()||(mode==='puzzle'&&api.solved()))return;const e=info.event;
if(info.type===B.PointerEventTypes.POINTERDOWN&&e.button===0){const hit=pickInteractive();if(mode==='puzzle'){pointer={x:e.clientX,y:e.clientY,meta:hit.pickedMesh?.metadata,point:hit.pickedPoint,moved:false};if(pointer.meta?.clock)clockAt(hit);}else{const groundHit=scene.pick(scene.pointerX,scene.pointerY,m=>m===ground);if(groundHit.hit)destination=groundHit.pickedPoint;}}
if(info.type===B.PointerEventTypes.POINTERMOVE&&pointer){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>10)pointer.moved=true;if(pointer.meta?.clock){const hit=scene.pick(scene.pointerX,scene.pointerY,m=>m===board||m===ground);clockAt(hit);}else if(pointer.moved&&pointer.meta?.drag){if(!dragVisual)dragVisual=ell('held-puzzle-object',[0,0,0],[.35,.35,.35],pointer.meta.colour===1?pink:warm);const hit=scene.pick(scene.pointerX,scene.pointerY,m=>m===board||m===ground);if(hit.hit)dragVisual.position.copyFrom(hit.pickedPoint.add(new B.Vector3(0,.65,0)));}}
if(info.type===B.PointerEventTypes.POINTERUP&&pointer){const p=pointer;pointer=null;const hit=pickInteractive(),target=hit.pickedMesh?.metadata;dragVisual?.dispose();dragVisual=null;if(!p.moved){if(!p.meta?.clock)p.meta?.use?.();}else if(p.meta?.drag==='drop'&&target?.drop==='drop'){selected=p.meta.colour;api.select(selected);target.use();}else if(p.meta?.drag==='firefly'&&target?.drop==='firefly'){target.use();}else if(p.meta?.drag==='letter'&&hit.hit){p.meta.use();}}
});canvas.addEventListener('pointercancel',()=>{pointer=null;dragVisual?.dispose();dragVisual=null;});ground.isPickable=true;
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||api.blocked())return;keys[e.key.toLowerCase()]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='e'&&mode==='world'&&wasNear)api.interact(wasNear);if(mode==='puzzle'&&['ArrowLeft','ArrowRight','Enter',' '].includes(e.key)){if(e.key==='ArrowLeft')objectsIndex=(objectsIndex-1+objects.length)%objects.length;if(e.key==='ArrowRight')objectsIndex=(objectsIndex+1)%objects.length;if(e.key==='Enter'||e.key===' ')objects[objectsIndex]?.fn();api.objects(objects.map(o=>o.name),objectsIndex);}});window.addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);window.addEventListener('blur',()=>{keys={};stick={x:0,y:0};});window.addEventListener('resize',()=>engine.resize());
engine.runRenderLoop(()=>{const dt=Math.min(engine.getDeltaTime()/1000,.04);if(document.hidden)return;paused=api.blocked();if(!paused){time+=dt;const reduced=prefs().motion;const goal=api.goal(),target=sites[goal];beacon.setEnabled(!!target&&mode==='world');if(target){beacon.position.set(target.x,5.3+(reduced?0:Math.sin(time*2)*.2),target.z);beacon.rotation.z=reduced?0:time*.25;}
if(!reduced){fireflies.forEach((m,i)=>{m.position.y=1.6+Math.sin(time+i)*.6;});ghost.position.y=2+Math.sin(time*2)*.12;waterRipples.forEach((r,i)=>{const s=.8+((time*.2+i*.13)%1);r.scaling.x=r.scaling.z=s;});moonMachine.rotation.z=time*.08;}
if(mode==='world'){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+stick.x,z=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+stick.y;const length=Math.hypot(x,z);moving=started&&length>.1;let dir=new B.Vector3();if(moving){const forward=new B.Vector3(-Math.cos(camera.alpha),0,-Math.sin(camera.alpha)),right=new B.Vector3(forward.z,0,-forward.x);dir=right.scale(x).add(forward.scale(-z)).normalize();destination=null;}else if(started&&destination){dir=destination.subtract(hero.position);dir.y=0;if(dir.length()<.3)destination=null;else{dir.normalize();moving=true;}}if(moving){const next=hero.position.add(dir.scale(dt*5));if(Math.abs(next.x)<55&&next.z>-40&&next.z<60){const obstacle=obstacles.some(o=>Math.abs(next.x-o.x)<o.w/2&&Math.abs(next.z-o.z)<o.d/2);if(!obstacle)hero.position.copyFrom(next);}hero.rotation.y=Math.atan2(-dir.x,-dir.z);if(!reduced)limbs.forEach((m,i)=>m.rotation.x=Math.sin(time*8+(i%2)*Math.PI)*.4);}else limbs.forEach(m=>m.rotation.x*=.85);
if(rideTime>0){rideTime-=dt;if(reduced||rideTime<=0){hero.position.set(12,0,28);rideTime=0;}else{hero.position.set(12,Math.sin((1-rideTime/4)*Math.PI)*1.1,12+(1-rideTime/4)*16);train.position.z=hero.position.z;}}else train.position.z=12;
if(started){camera.setTarget(hero.position.add(new B.Vector3(0,1.3,0)));}else{camera.alpha=-Math.PI/2+.2;camera.beta=.92;camera.radius=28;camera.setTarget(new B.Vector3(0,2,4));}
ghost.position.x+=(hero.position.x+1.2-ghost.position.x)*Math.min(1,dt*4);ghost.position.z+=(hero.position.z+.3-ghost.position.z)*Math.min(1,dt*4);ghost.rotation.y=hero.rotation.y;
let near=null,min=5;for(const [area,p]of Object.entries(sites)){const d=Math.hypot(hero.position.x-p.x,hero.position.z-p.z);if(d<min){near=area;min=d;}}if(near!==wasNear){wasNear=near;api.near(near);}api.ride(Math.hypot(hero.position.x-12,hero.position.z-12)<4);if(moving&&Math.floor(time*10)%30===0)api.position(hero.position.x,hero.position.z);
}
}scene.render();if(quality==='auto'&&engine.getFps()<24&&time>4&&slow++>120){qualitySet('low');slow=0;}});
qualitySet('auto');return{engine,scene,hero,camera,sites,start(pos){started=true;if(pos&&Number.isFinite(pos.x)&&Number.isFinite(pos.z)&&Math.abs(pos.x)<55&&pos.z>-40&&pos.z<60)hero.position.set(pos.x,0,pos.z);},enter,leave,teleport,change(a){answer=a;renderPuzzle();},select(i){selected=i;},objectsMove(d){if(!objects.length)return;objectsIndex=(objectsIndex+d+objects.length)%objects.length;api.objects(objects.map(o=>o.name),objectsIndex);},objectsUse(){objects[objectsIndex]?.fn();},celebration,updateWorld,setStick(x,y){stick={x,y};},quality:qualitySet,avatar(coat,skin){coatMat.diffuseColor=B.Color3.FromHexString({teal:'#4caaaa',plum:'#ab79a3',amber:'#d5a254'}[coat]||'#4caaaa');skinMat.diffuseColor=B.Color3.FromHexString({light:'#d7aa86',medium:'#ac785a',dark:'#714a39'}[skin]||'#d7aa86');},ride(){if(rideTime||mode!=='world')return;rideTime=4;api.effect('travel');},stop(){engine.dispose();}};
}
root.MoonWorld={create};})(window);
